// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

package com.upuphub.dew.community.connection.protobuf.account;

/**
 * Protobuf type {@code GeneralProfile}
 */
public  final class GeneralProfile extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GeneralProfile)
    GeneralProfileOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GeneralProfile.newBuilder() to construct.
  private GeneralProfile(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GeneralProfile() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GeneralProfile();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GeneralProfile(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            uin_ = input.readInt64();
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              profile_ = com.google.protobuf.MapField.newMapField(
                  ProfileDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            profile__ = input.readMessage(
                ProfileDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            profile_.getMutableMap().put(
                profile__.getKey(), profile__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.upuphub.dew.community.connection.protobuf.account.Account.internal_static_GeneralProfile_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 2:
        return internalGetProfile();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.upuphub.dew.community.connection.protobuf.account.Account.internal_static_GeneralProfile_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.upuphub.dew.community.connection.protobuf.account.GeneralProfile.class, com.upuphub.dew.community.connection.protobuf.account.GeneralProfile.Builder.class);
  }

  public static final int UIN_FIELD_NUMBER = 1;
  private long uin_;
  /**
   * <pre>
   * 通用Profile的uin
   * </pre>
   *
   * <code>int64 uin = 1;</code>
   */
  public long getUin() {
    return uin_;
  }

  public static final int PROFILE_FIELD_NUMBER = 2;
  private static final class ProfileDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.upuphub.dew.community.connection.protobuf.account.Account.internal_static_GeneralProfile_ProfileEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> profile_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetProfile() {
    if (profile_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          ProfileDefaultEntryHolder.defaultEntry);
    }
    return profile_;
  }

  public int getProfileCount() {
    return internalGetProfile().getMap().size();
  }
  /**
   * <pre>
   * 通用Profile的具体信息
   * </pre>
   *
   * <code>map&lt;string, string&gt; profile = 2;</code>
   */

  public boolean containsProfile(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetProfile().getMap().containsKey(key);
  }
  /**
   * Use {@link #getProfileMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getProfile() {
    return getProfileMap();
  }
  /**
   * <pre>
   * 通用Profile的具体信息
   * </pre>
   *
   * <code>map&lt;string, string&gt; profile = 2;</code>
   */

  public java.util.Map<java.lang.String, java.lang.String> getProfileMap() {
    return internalGetProfile().getMap();
  }
  /**
   * <pre>
   * 通用Profile的具体信息
   * </pre>
   *
   * <code>map&lt;string, string&gt; profile = 2;</code>
   */

  public java.lang.String getProfileOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetProfile().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * 通用Profile的具体信息
   * </pre>
   *
   * <code>map&lt;string, string&gt; profile = 2;</code>
   */

  public java.lang.String getProfileOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetProfile().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (uin_ != 0L) {
      output.writeInt64(1, uin_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetProfile(),
        ProfileDefaultEntryHolder.defaultEntry,
        2);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (uin_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, uin_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetProfile().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      profile__ = ProfileDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, profile__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.upuphub.dew.community.connection.protobuf.account.GeneralProfile)) {
      return super.equals(obj);
    }
    com.upuphub.dew.community.connection.protobuf.account.GeneralProfile other = (com.upuphub.dew.community.connection.protobuf.account.GeneralProfile) obj;

    if (getUin()
        != other.getUin()) return false;
    if (!internalGetProfile().equals(
        other.internalGetProfile())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + UIN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUin());
    if (!internalGetProfile().getMap().isEmpty()) {
      hash = (37 * hash) + PROFILE_FIELD_NUMBER;
      hash = (53 * hash) + internalGetProfile().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.upuphub.dew.community.connection.protobuf.account.GeneralProfile parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.upuphub.dew.community.connection.protobuf.account.GeneralProfile parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.upuphub.dew.community.connection.protobuf.account.GeneralProfile parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.upuphub.dew.community.connection.protobuf.account.GeneralProfile parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.upuphub.dew.community.connection.protobuf.account.GeneralProfile parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.upuphub.dew.community.connection.protobuf.account.GeneralProfile parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.upuphub.dew.community.connection.protobuf.account.GeneralProfile parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.upuphub.dew.community.connection.protobuf.account.GeneralProfile parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.upuphub.dew.community.connection.protobuf.account.GeneralProfile parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.upuphub.dew.community.connection.protobuf.account.GeneralProfile parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.upuphub.dew.community.connection.protobuf.account.GeneralProfile parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.upuphub.dew.community.connection.protobuf.account.GeneralProfile parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.upuphub.dew.community.connection.protobuf.account.GeneralProfile prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GeneralProfile}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GeneralProfile)
      com.upuphub.dew.community.connection.protobuf.account.GeneralProfileOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.upuphub.dew.community.connection.protobuf.account.Account.internal_static_GeneralProfile_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetProfile();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetMutableProfile();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.upuphub.dew.community.connection.protobuf.account.Account.internal_static_GeneralProfile_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.upuphub.dew.community.connection.protobuf.account.GeneralProfile.class, com.upuphub.dew.community.connection.protobuf.account.GeneralProfile.Builder.class);
    }

    // Construct using com.upuphub.dew.community.connection.protobuf.account.GeneralProfile.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      uin_ = 0L;

      internalGetMutableProfile().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.upuphub.dew.community.connection.protobuf.account.Account.internal_static_GeneralProfile_descriptor;
    }

    @java.lang.Override
    public com.upuphub.dew.community.connection.protobuf.account.GeneralProfile getDefaultInstanceForType() {
      return com.upuphub.dew.community.connection.protobuf.account.GeneralProfile.getDefaultInstance();
    }

    @java.lang.Override
    public com.upuphub.dew.community.connection.protobuf.account.GeneralProfile build() {
      com.upuphub.dew.community.connection.protobuf.account.GeneralProfile result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.upuphub.dew.community.connection.protobuf.account.GeneralProfile buildPartial() {
      com.upuphub.dew.community.connection.protobuf.account.GeneralProfile result = new com.upuphub.dew.community.connection.protobuf.account.GeneralProfile(this);
      int from_bitField0_ = bitField0_;
      result.uin_ = uin_;
      result.profile_ = internalGetProfile();
      result.profile_.makeImmutable();
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.upuphub.dew.community.connection.protobuf.account.GeneralProfile) {
        return mergeFrom((com.upuphub.dew.community.connection.protobuf.account.GeneralProfile)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.upuphub.dew.community.connection.protobuf.account.GeneralProfile other) {
      if (other == com.upuphub.dew.community.connection.protobuf.account.GeneralProfile.getDefaultInstance()) return this;
      if (other.getUin() != 0L) {
        setUin(other.getUin());
      }
      internalGetMutableProfile().mergeFrom(
          other.internalGetProfile());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.upuphub.dew.community.connection.protobuf.account.GeneralProfile parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.upuphub.dew.community.connection.protobuf.account.GeneralProfile) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long uin_ ;
    /**
     * <pre>
     * 通用Profile的uin
     * </pre>
     *
     * <code>int64 uin = 1;</code>
     */
    public long getUin() {
      return uin_;
    }
    /**
     * <pre>
     * 通用Profile的uin
     * </pre>
     *
     * <code>int64 uin = 1;</code>
     */
    public Builder setUin(long value) {
      
      uin_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 通用Profile的uin
     * </pre>
     *
     * <code>int64 uin = 1;</code>
     */
    public Builder clearUin() {
      
      uin_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> profile_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetProfile() {
      if (profile_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ProfileDefaultEntryHolder.defaultEntry);
      }
      return profile_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableProfile() {
      onChanged();;
      if (profile_ == null) {
        profile_ = com.google.protobuf.MapField.newMapField(
            ProfileDefaultEntryHolder.defaultEntry);
      }
      if (!profile_.isMutable()) {
        profile_ = profile_.copy();
      }
      return profile_;
    }

    public int getProfileCount() {
      return internalGetProfile().getMap().size();
    }
    /**
     * <pre>
     * 通用Profile的具体信息
     * </pre>
     *
     * <code>map&lt;string, string&gt; profile = 2;</code>
     */

    public boolean containsProfile(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetProfile().getMap().containsKey(key);
    }
    /**
     * Use {@link #getProfileMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getProfile() {
      return getProfileMap();
    }
    /**
     * <pre>
     * 通用Profile的具体信息
     * </pre>
     *
     * <code>map&lt;string, string&gt; profile = 2;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getProfileMap() {
      return internalGetProfile().getMap();
    }
    /**
     * <pre>
     * 通用Profile的具体信息
     * </pre>
     *
     * <code>map&lt;string, string&gt; profile = 2;</code>
     */

    public java.lang.String getProfileOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetProfile().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * 通用Profile的具体信息
     * </pre>
     *
     * <code>map&lt;string, string&gt; profile = 2;</code>
     */

    public java.lang.String getProfileOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetProfile().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearProfile() {
      internalGetMutableProfile().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * 通用Profile的具体信息
     * </pre>
     *
     * <code>map&lt;string, string&gt; profile = 2;</code>
     */

    public Builder removeProfile(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableProfile().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableProfile() {
      return internalGetMutableProfile().getMutableMap();
    }
    /**
     * <pre>
     * 通用Profile的具体信息
     * </pre>
     *
     * <code>map&lt;string, string&gt; profile = 2;</code>
     */
    public Builder putProfile(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableProfile().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <pre>
     * 通用Profile的具体信息
     * </pre>
     *
     * <code>map&lt;string, string&gt; profile = 2;</code>
     */

    public Builder putAllProfile(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableProfile().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GeneralProfile)
  }

  // @@protoc_insertion_point(class_scope:GeneralProfile)
  private static final com.upuphub.dew.community.connection.protobuf.account.GeneralProfile DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.upuphub.dew.community.connection.protobuf.account.GeneralProfile();
  }

  public static com.upuphub.dew.community.connection.protobuf.account.GeneralProfile getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GeneralProfile>
      PARSER = new com.google.protobuf.AbstractParser<GeneralProfile>() {
    @java.lang.Override
    public GeneralProfile parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GeneralProfile(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GeneralProfile> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GeneralProfile> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.upuphub.dew.community.connection.protobuf.account.GeneralProfile getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

