// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

package com.upuphub.dew.community.connection.protobuf.account;

public interface GeneralProfileOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GeneralProfile)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 通用Profile的uin
   * </pre>
   *
   * <code>int64 uin = 1;</code>
   */
  long getUin();

  /**
   * <pre>
   * 通用Profile的具体信息
   * </pre>
   *
   * <code>map&lt;string, string&gt; profile = 2;</code>
   */
  int getProfileCount();
  /**
   * <pre>
   * 通用Profile的具体信息
   * </pre>
   *
   * <code>map&lt;string, string&gt; profile = 2;</code>
   */
  boolean containsProfile(
      java.lang.String key);
  /**
   * Use {@link #getProfileMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getProfile();
  /**
   * <pre>
   * 通用Profile的具体信息
   * </pre>
   *
   * <code>map&lt;string, string&gt; profile = 2;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getProfileMap();
  /**
   * <pre>
   * 通用Profile的具体信息
   * </pre>
   *
   * <code>map&lt;string, string&gt; profile = 2;</code>
   */

  java.lang.String getProfileOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <pre>
   * 通用Profile的具体信息
   * </pre>
   *
   * <code>map&lt;string, string&gt; profile = 2;</code>
   */

  java.lang.String getProfileOrThrow(
      java.lang.String key);
}
