// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

package com.upuphub.dew.community.connection.protobuf.account;

public interface LastLoginInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LastLoginInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 用户最后登录设备
   * </pre>
   *
   * <code>string device = 1;</code>
   */
  java.lang.String getDevice();
  /**
   * <pre>
   * 用户最后登录设备
   * </pre>
   *
   * <code>string device = 1;</code>
   */
  com.google.protobuf.ByteString
      getDeviceBytes();

  /**
   * <pre>
   * 用户最后登录时间
   * </pre>
   *
   * <code>int64 LastLoginTime = 2;</code>
   */
  long getLastLoginTime();

  /**
   * <pre>
   * 最后登录的Ip地址
   * </pre>
   *
   * <code>string lastLoginIpAddr = 3;</code>
   */
  java.lang.String getLastLoginIpAddr();
  /**
   * <pre>
   * 最后登录的Ip地址
   * </pre>
   *
   * <code>string lastLoginIpAddr = 3;</code>
   */
  com.google.protobuf.ByteString
      getLastLoginIpAddrBytes();
}
