// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

package com.upuphub.dew.community.connection.protobuf.account;

public interface LocationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Location)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 经度
   * </pre>
   *
   * <code>double longitude = 1;</code>
   */
  double getLongitude();

  /**
   * <pre>
   * 纬度
   * </pre>
   *
   * <code>double latitude = 2;</code>
   */
  double getLatitude();

  /**
   * <pre>
   * 国家
   * </pre>
   *
   * <code>string country = 3;</code>
   */
  java.lang.String getCountry();
  /**
   * <pre>
   * 国家
   * </pre>
   *
   * <code>string country = 3;</code>
   */
  com.google.protobuf.ByteString
      getCountryBytes();

  /**
   * <pre>
   * 省份
   * </pre>
   *
   * <code>string province = 4;</code>
   */
  java.lang.String getProvince();
  /**
   * <pre>
   * 省份
   * </pre>
   *
   * <code>string province = 4;</code>
   */
  com.google.protobuf.ByteString
      getProvinceBytes();

  /**
   * <pre>
   * 城市
   * </pre>
   *
   * <code>string city = 5;</code>
   */
  java.lang.String getCity();
  /**
   * <pre>
   * 城市
   * </pre>
   *
   * <code>string city = 5;</code>
   */
  com.google.protobuf.ByteString
      getCityBytes();

  /**
   * <pre>
   * 县/区
   * </pre>
   *
   * <code>string district = 6;</code>
   */
  java.lang.String getDistrict();
  /**
   * <pre>
   * 县/区
   * </pre>
   *
   * <code>string district = 6;</code>
   */
  com.google.protobuf.ByteString
      getDistrictBytes();

  /**
   * <pre>
   * 街道
   * </pre>
   *
   * <code>string street = 7;</code>
   */
  java.lang.String getStreet();
  /**
   * <pre>
   * 街道
   * </pre>
   *
   * <code>string street = 7;</code>
   */
  com.google.protobuf.ByteString
      getStreetBytes();

  /**
   * <pre>
   * 用户Uin
   * </pre>
   *
   * <code>int64 uin = 8;</code>
   */
  long getUin();
}
