// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

package com.upuphub.dew.community.connection.protobuf.account;

/**
 * Protobuf type {@code Profile}
 */
public  final class Profile extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Profile)
    ProfileOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Profile.newBuilder() to construct.
  private Profile(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Profile() {
    secretKey_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Profile();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Profile(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            uin_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            secretKey_ = s;
            break;
          }
          case 26: {
            com.upuphub.dew.community.connection.protobuf.account.UsrProfile.Builder subBuilder = null;
            if (usrProfile_ != null) {
              subBuilder = usrProfile_.toBuilder();
            }
            usrProfile_ = input.readMessage(com.upuphub.dew.community.connection.protobuf.account.UsrProfile.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(usrProfile_);
              usrProfile_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag.Builder subBuilder = null;
            if (usrStatusFlag_ != null) {
              subBuilder = usrStatusFlag_.toBuilder();
            }
            usrStatusFlag_ = input.readMessage(com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(usrStatusFlag_);
              usrStatusFlag_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            com.upuphub.dew.community.connection.protobuf.account.LastLoginInfo.Builder subBuilder = null;
            if (lastLoginInfo_ != null) {
              subBuilder = lastLoginInfo_.toBuilder();
            }
            lastLoginInfo_ = input.readMessage(com.upuphub.dew.community.connection.protobuf.account.LastLoginInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(lastLoginInfo_);
              lastLoginInfo_ = subBuilder.buildPartial();
            }

            break;
          }
          case 48: {

            errorCode_ = input.readInt32();
            break;
          }
          case 56: {

            profileCompletion_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.upuphub.dew.community.connection.protobuf.account.Account.internal_static_Profile_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.upuphub.dew.community.connection.protobuf.account.Account.internal_static_Profile_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.upuphub.dew.community.connection.protobuf.account.Profile.class, com.upuphub.dew.community.connection.protobuf.account.Profile.Builder.class);
  }

  public static final int UIN_FIELD_NUMBER = 1;
  private long uin_;
  /**
   * <pre>
   * 用户uin
   * </pre>
   *
   * <code>int64 uin = 1;</code>
   */
  public long getUin() {
    return uin_;
  }

  public static final int SECRETKEY_FIELD_NUMBER = 2;
  private volatile java.lang.Object secretKey_;
  /**
   * <pre>
   * 用户SecretKey
   * </pre>
   *
   * <code>string secretKey = 2;</code>
   */
  public java.lang.String getSecretKey() {
    java.lang.Object ref = secretKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      secretKey_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 用户SecretKey
   * </pre>
   *
   * <code>string secretKey = 2;</code>
   */
  public com.google.protobuf.ByteString
      getSecretKeyBytes() {
    java.lang.Object ref = secretKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      secretKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USRPROFILE_FIELD_NUMBER = 3;
  private com.upuphub.dew.community.connection.protobuf.account.UsrProfile usrProfile_;
  /**
   * <pre>
   * 用户基础信息
   * </pre>
   *
   * <code>.UsrProfile usrProfile = 3;</code>
   */
  public boolean hasUsrProfile() {
    return usrProfile_ != null;
  }
  /**
   * <pre>
   * 用户基础信息
   * </pre>
   *
   * <code>.UsrProfile usrProfile = 3;</code>
   */
  public com.upuphub.dew.community.connection.protobuf.account.UsrProfile getUsrProfile() {
    return usrProfile_ == null ? com.upuphub.dew.community.connection.protobuf.account.UsrProfile.getDefaultInstance() : usrProfile_;
  }
  /**
   * <pre>
   * 用户基础信息
   * </pre>
   *
   * <code>.UsrProfile usrProfile = 3;</code>
   */
  public com.upuphub.dew.community.connection.protobuf.account.UsrProfileOrBuilder getUsrProfileOrBuilder() {
    return getUsrProfile();
  }

  public static final int USRSTATUSFLAG_FIELD_NUMBER = 4;
  private com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag usrStatusFlag_;
  /**
   * <pre>
   * 用户账号标识
   * </pre>
   *
   * <code>.UsrStatusFlag usrStatusFlag = 4;</code>
   */
  public boolean hasUsrStatusFlag() {
    return usrStatusFlag_ != null;
  }
  /**
   * <pre>
   * 用户账号标识
   * </pre>
   *
   * <code>.UsrStatusFlag usrStatusFlag = 4;</code>
   */
  public com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag getUsrStatusFlag() {
    return usrStatusFlag_ == null ? com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag.getDefaultInstance() : usrStatusFlag_;
  }
  /**
   * <pre>
   * 用户账号标识
   * </pre>
   *
   * <code>.UsrStatusFlag usrStatusFlag = 4;</code>
   */
  public com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlagOrBuilder getUsrStatusFlagOrBuilder() {
    return getUsrStatusFlag();
  }

  public static final int LASTLOGININFO_FIELD_NUMBER = 5;
  private com.upuphub.dew.community.connection.protobuf.account.LastLoginInfo lastLoginInfo_;
  /**
   * <pre>
   * 用户最后登录信息
   * </pre>
   *
   * <code>.LastLoginInfo lastLoginInfo = 5;</code>
   */
  public boolean hasLastLoginInfo() {
    return lastLoginInfo_ != null;
  }
  /**
   * <pre>
   * 用户最后登录信息
   * </pre>
   *
   * <code>.LastLoginInfo lastLoginInfo = 5;</code>
   */
  public com.upuphub.dew.community.connection.protobuf.account.LastLoginInfo getLastLoginInfo() {
    return lastLoginInfo_ == null ? com.upuphub.dew.community.connection.protobuf.account.LastLoginInfo.getDefaultInstance() : lastLoginInfo_;
  }
  /**
   * <pre>
   * 用户最后登录信息
   * </pre>
   *
   * <code>.LastLoginInfo lastLoginInfo = 5;</code>
   */
  public com.upuphub.dew.community.connection.protobuf.account.LastLoginInfoOrBuilder getLastLoginInfoOrBuilder() {
    return getLastLoginInfo();
  }

  public static final int ERRORCODE_FIELD_NUMBER = 6;
  private int errorCode_;
  /**
   * <pre>
   * 请求错误码
   * </pre>
   *
   * <code>int32 errorCode = 6;</code>
   */
  public int getErrorCode() {
    return errorCode_;
  }

  public static final int PROFILECOMPLETION_FIELD_NUMBER = 7;
  private int profileCompletion_;
  /**
   * <pre>
   * 信息完成度
   * </pre>
   *
   * <code>int32 profileCompletion = 7;</code>
   */
  public int getProfileCompletion() {
    return profileCompletion_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (uin_ != 0L) {
      output.writeInt64(1, uin_);
    }
    if (!getSecretKeyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, secretKey_);
    }
    if (usrProfile_ != null) {
      output.writeMessage(3, getUsrProfile());
    }
    if (usrStatusFlag_ != null) {
      output.writeMessage(4, getUsrStatusFlag());
    }
    if (lastLoginInfo_ != null) {
      output.writeMessage(5, getLastLoginInfo());
    }
    if (errorCode_ != 0) {
      output.writeInt32(6, errorCode_);
    }
    if (profileCompletion_ != 0) {
      output.writeInt32(7, profileCompletion_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (uin_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, uin_);
    }
    if (!getSecretKeyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, secretKey_);
    }
    if (usrProfile_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getUsrProfile());
    }
    if (usrStatusFlag_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getUsrStatusFlag());
    }
    if (lastLoginInfo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getLastLoginInfo());
    }
    if (errorCode_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, errorCode_);
    }
    if (profileCompletion_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, profileCompletion_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.upuphub.dew.community.connection.protobuf.account.Profile)) {
      return super.equals(obj);
    }
    com.upuphub.dew.community.connection.protobuf.account.Profile other = (com.upuphub.dew.community.connection.protobuf.account.Profile) obj;

    if (getUin()
        != other.getUin()) return false;
    if (!getSecretKey()
        .equals(other.getSecretKey())) return false;
    if (hasUsrProfile() != other.hasUsrProfile()) return false;
    if (hasUsrProfile()) {
      if (!getUsrProfile()
          .equals(other.getUsrProfile())) return false;
    }
    if (hasUsrStatusFlag() != other.hasUsrStatusFlag()) return false;
    if (hasUsrStatusFlag()) {
      if (!getUsrStatusFlag()
          .equals(other.getUsrStatusFlag())) return false;
    }
    if (hasLastLoginInfo() != other.hasLastLoginInfo()) return false;
    if (hasLastLoginInfo()) {
      if (!getLastLoginInfo()
          .equals(other.getLastLoginInfo())) return false;
    }
    if (getErrorCode()
        != other.getErrorCode()) return false;
    if (getProfileCompletion()
        != other.getProfileCompletion()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + UIN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUin());
    hash = (37 * hash) + SECRETKEY_FIELD_NUMBER;
    hash = (53 * hash) + getSecretKey().hashCode();
    if (hasUsrProfile()) {
      hash = (37 * hash) + USRPROFILE_FIELD_NUMBER;
      hash = (53 * hash) + getUsrProfile().hashCode();
    }
    if (hasUsrStatusFlag()) {
      hash = (37 * hash) + USRSTATUSFLAG_FIELD_NUMBER;
      hash = (53 * hash) + getUsrStatusFlag().hashCode();
    }
    if (hasLastLoginInfo()) {
      hash = (37 * hash) + LASTLOGININFO_FIELD_NUMBER;
      hash = (53 * hash) + getLastLoginInfo().hashCode();
    }
    hash = (37 * hash) + ERRORCODE_FIELD_NUMBER;
    hash = (53 * hash) + getErrorCode();
    hash = (37 * hash) + PROFILECOMPLETION_FIELD_NUMBER;
    hash = (53 * hash) + getProfileCompletion();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.upuphub.dew.community.connection.protobuf.account.Profile parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.upuphub.dew.community.connection.protobuf.account.Profile parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.upuphub.dew.community.connection.protobuf.account.Profile parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.upuphub.dew.community.connection.protobuf.account.Profile parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.upuphub.dew.community.connection.protobuf.account.Profile parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.upuphub.dew.community.connection.protobuf.account.Profile parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.upuphub.dew.community.connection.protobuf.account.Profile parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.upuphub.dew.community.connection.protobuf.account.Profile parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.upuphub.dew.community.connection.protobuf.account.Profile parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.upuphub.dew.community.connection.protobuf.account.Profile parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.upuphub.dew.community.connection.protobuf.account.Profile parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.upuphub.dew.community.connection.protobuf.account.Profile parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.upuphub.dew.community.connection.protobuf.account.Profile prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Profile}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Profile)
      com.upuphub.dew.community.connection.protobuf.account.ProfileOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.upuphub.dew.community.connection.protobuf.account.Account.internal_static_Profile_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.upuphub.dew.community.connection.protobuf.account.Account.internal_static_Profile_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.upuphub.dew.community.connection.protobuf.account.Profile.class, com.upuphub.dew.community.connection.protobuf.account.Profile.Builder.class);
    }

    // Construct using com.upuphub.dew.community.connection.protobuf.account.Profile.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      uin_ = 0L;

      secretKey_ = "";

      if (usrProfileBuilder_ == null) {
        usrProfile_ = null;
      } else {
        usrProfile_ = null;
        usrProfileBuilder_ = null;
      }
      if (usrStatusFlagBuilder_ == null) {
        usrStatusFlag_ = null;
      } else {
        usrStatusFlag_ = null;
        usrStatusFlagBuilder_ = null;
      }
      if (lastLoginInfoBuilder_ == null) {
        lastLoginInfo_ = null;
      } else {
        lastLoginInfo_ = null;
        lastLoginInfoBuilder_ = null;
      }
      errorCode_ = 0;

      profileCompletion_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.upuphub.dew.community.connection.protobuf.account.Account.internal_static_Profile_descriptor;
    }

    @java.lang.Override
    public com.upuphub.dew.community.connection.protobuf.account.Profile getDefaultInstanceForType() {
      return com.upuphub.dew.community.connection.protobuf.account.Profile.getDefaultInstance();
    }

    @java.lang.Override
    public com.upuphub.dew.community.connection.protobuf.account.Profile build() {
      com.upuphub.dew.community.connection.protobuf.account.Profile result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.upuphub.dew.community.connection.protobuf.account.Profile buildPartial() {
      com.upuphub.dew.community.connection.protobuf.account.Profile result = new com.upuphub.dew.community.connection.protobuf.account.Profile(this);
      result.uin_ = uin_;
      result.secretKey_ = secretKey_;
      if (usrProfileBuilder_ == null) {
        result.usrProfile_ = usrProfile_;
      } else {
        result.usrProfile_ = usrProfileBuilder_.build();
      }
      if (usrStatusFlagBuilder_ == null) {
        result.usrStatusFlag_ = usrStatusFlag_;
      } else {
        result.usrStatusFlag_ = usrStatusFlagBuilder_.build();
      }
      if (lastLoginInfoBuilder_ == null) {
        result.lastLoginInfo_ = lastLoginInfo_;
      } else {
        result.lastLoginInfo_ = lastLoginInfoBuilder_.build();
      }
      result.errorCode_ = errorCode_;
      result.profileCompletion_ = profileCompletion_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.upuphub.dew.community.connection.protobuf.account.Profile) {
        return mergeFrom((com.upuphub.dew.community.connection.protobuf.account.Profile)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.upuphub.dew.community.connection.protobuf.account.Profile other) {
      if (other == com.upuphub.dew.community.connection.protobuf.account.Profile.getDefaultInstance()) return this;
      if (other.getUin() != 0L) {
        setUin(other.getUin());
      }
      if (!other.getSecretKey().isEmpty()) {
        secretKey_ = other.secretKey_;
        onChanged();
      }
      if (other.hasUsrProfile()) {
        mergeUsrProfile(other.getUsrProfile());
      }
      if (other.hasUsrStatusFlag()) {
        mergeUsrStatusFlag(other.getUsrStatusFlag());
      }
      if (other.hasLastLoginInfo()) {
        mergeLastLoginInfo(other.getLastLoginInfo());
      }
      if (other.getErrorCode() != 0) {
        setErrorCode(other.getErrorCode());
      }
      if (other.getProfileCompletion() != 0) {
        setProfileCompletion(other.getProfileCompletion());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.upuphub.dew.community.connection.protobuf.account.Profile parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.upuphub.dew.community.connection.protobuf.account.Profile) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long uin_ ;
    /**
     * <pre>
     * 用户uin
     * </pre>
     *
     * <code>int64 uin = 1;</code>
     */
    public long getUin() {
      return uin_;
    }
    /**
     * <pre>
     * 用户uin
     * </pre>
     *
     * <code>int64 uin = 1;</code>
     */
    public Builder setUin(long value) {
      
      uin_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户uin
     * </pre>
     *
     * <code>int64 uin = 1;</code>
     */
    public Builder clearUin() {
      
      uin_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object secretKey_ = "";
    /**
     * <pre>
     * 用户SecretKey
     * </pre>
     *
     * <code>string secretKey = 2;</code>
     */
    public java.lang.String getSecretKey() {
      java.lang.Object ref = secretKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        secretKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 用户SecretKey
     * </pre>
     *
     * <code>string secretKey = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSecretKeyBytes() {
      java.lang.Object ref = secretKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        secretKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 用户SecretKey
     * </pre>
     *
     * <code>string secretKey = 2;</code>
     */
    public Builder setSecretKey(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      secretKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户SecretKey
     * </pre>
     *
     * <code>string secretKey = 2;</code>
     */
    public Builder clearSecretKey() {
      
      secretKey_ = getDefaultInstance().getSecretKey();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户SecretKey
     * </pre>
     *
     * <code>string secretKey = 2;</code>
     */
    public Builder setSecretKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      secretKey_ = value;
      onChanged();
      return this;
    }

    private com.upuphub.dew.community.connection.protobuf.account.UsrProfile usrProfile_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.upuphub.dew.community.connection.protobuf.account.UsrProfile, com.upuphub.dew.community.connection.protobuf.account.UsrProfile.Builder, com.upuphub.dew.community.connection.protobuf.account.UsrProfileOrBuilder> usrProfileBuilder_;
    /**
     * <pre>
     * 用户基础信息
     * </pre>
     *
     * <code>.UsrProfile usrProfile = 3;</code>
     */
    public boolean hasUsrProfile() {
      return usrProfileBuilder_ != null || usrProfile_ != null;
    }
    /**
     * <pre>
     * 用户基础信息
     * </pre>
     *
     * <code>.UsrProfile usrProfile = 3;</code>
     */
    public com.upuphub.dew.community.connection.protobuf.account.UsrProfile getUsrProfile() {
      if (usrProfileBuilder_ == null) {
        return usrProfile_ == null ? com.upuphub.dew.community.connection.protobuf.account.UsrProfile.getDefaultInstance() : usrProfile_;
      } else {
        return usrProfileBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 用户基础信息
     * </pre>
     *
     * <code>.UsrProfile usrProfile = 3;</code>
     */
    public Builder setUsrProfile(com.upuphub.dew.community.connection.protobuf.account.UsrProfile value) {
      if (usrProfileBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        usrProfile_ = value;
        onChanged();
      } else {
        usrProfileBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 用户基础信息
     * </pre>
     *
     * <code>.UsrProfile usrProfile = 3;</code>
     */
    public Builder setUsrProfile(
        com.upuphub.dew.community.connection.protobuf.account.UsrProfile.Builder builderForValue) {
      if (usrProfileBuilder_ == null) {
        usrProfile_ = builderForValue.build();
        onChanged();
      } else {
        usrProfileBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 用户基础信息
     * </pre>
     *
     * <code>.UsrProfile usrProfile = 3;</code>
     */
    public Builder mergeUsrProfile(com.upuphub.dew.community.connection.protobuf.account.UsrProfile value) {
      if (usrProfileBuilder_ == null) {
        if (usrProfile_ != null) {
          usrProfile_ =
            com.upuphub.dew.community.connection.protobuf.account.UsrProfile.newBuilder(usrProfile_).mergeFrom(value).buildPartial();
        } else {
          usrProfile_ = value;
        }
        onChanged();
      } else {
        usrProfileBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 用户基础信息
     * </pre>
     *
     * <code>.UsrProfile usrProfile = 3;</code>
     */
    public Builder clearUsrProfile() {
      if (usrProfileBuilder_ == null) {
        usrProfile_ = null;
        onChanged();
      } else {
        usrProfile_ = null;
        usrProfileBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 用户基础信息
     * </pre>
     *
     * <code>.UsrProfile usrProfile = 3;</code>
     */
    public com.upuphub.dew.community.connection.protobuf.account.UsrProfile.Builder getUsrProfileBuilder() {
      
      onChanged();
      return getUsrProfileFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 用户基础信息
     * </pre>
     *
     * <code>.UsrProfile usrProfile = 3;</code>
     */
    public com.upuphub.dew.community.connection.protobuf.account.UsrProfileOrBuilder getUsrProfileOrBuilder() {
      if (usrProfileBuilder_ != null) {
        return usrProfileBuilder_.getMessageOrBuilder();
      } else {
        return usrProfile_ == null ?
            com.upuphub.dew.community.connection.protobuf.account.UsrProfile.getDefaultInstance() : usrProfile_;
      }
    }
    /**
     * <pre>
     * 用户基础信息
     * </pre>
     *
     * <code>.UsrProfile usrProfile = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.upuphub.dew.community.connection.protobuf.account.UsrProfile, com.upuphub.dew.community.connection.protobuf.account.UsrProfile.Builder, com.upuphub.dew.community.connection.protobuf.account.UsrProfileOrBuilder> 
        getUsrProfileFieldBuilder() {
      if (usrProfileBuilder_ == null) {
        usrProfileBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.upuphub.dew.community.connection.protobuf.account.UsrProfile, com.upuphub.dew.community.connection.protobuf.account.UsrProfile.Builder, com.upuphub.dew.community.connection.protobuf.account.UsrProfileOrBuilder>(
                getUsrProfile(),
                getParentForChildren(),
                isClean());
        usrProfile_ = null;
      }
      return usrProfileBuilder_;
    }

    private com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag usrStatusFlag_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag, com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag.Builder, com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlagOrBuilder> usrStatusFlagBuilder_;
    /**
     * <pre>
     * 用户账号标识
     * </pre>
     *
     * <code>.UsrStatusFlag usrStatusFlag = 4;</code>
     */
    public boolean hasUsrStatusFlag() {
      return usrStatusFlagBuilder_ != null || usrStatusFlag_ != null;
    }
    /**
     * <pre>
     * 用户账号标识
     * </pre>
     *
     * <code>.UsrStatusFlag usrStatusFlag = 4;</code>
     */
    public com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag getUsrStatusFlag() {
      if (usrStatusFlagBuilder_ == null) {
        return usrStatusFlag_ == null ? com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag.getDefaultInstance() : usrStatusFlag_;
      } else {
        return usrStatusFlagBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 用户账号标识
     * </pre>
     *
     * <code>.UsrStatusFlag usrStatusFlag = 4;</code>
     */
    public Builder setUsrStatusFlag(com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag value) {
      if (usrStatusFlagBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        usrStatusFlag_ = value;
        onChanged();
      } else {
        usrStatusFlagBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 用户账号标识
     * </pre>
     *
     * <code>.UsrStatusFlag usrStatusFlag = 4;</code>
     */
    public Builder setUsrStatusFlag(
        com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag.Builder builderForValue) {
      if (usrStatusFlagBuilder_ == null) {
        usrStatusFlag_ = builderForValue.build();
        onChanged();
      } else {
        usrStatusFlagBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 用户账号标识
     * </pre>
     *
     * <code>.UsrStatusFlag usrStatusFlag = 4;</code>
     */
    public Builder mergeUsrStatusFlag(com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag value) {
      if (usrStatusFlagBuilder_ == null) {
        if (usrStatusFlag_ != null) {
          usrStatusFlag_ =
            com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag.newBuilder(usrStatusFlag_).mergeFrom(value).buildPartial();
        } else {
          usrStatusFlag_ = value;
        }
        onChanged();
      } else {
        usrStatusFlagBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 用户账号标识
     * </pre>
     *
     * <code>.UsrStatusFlag usrStatusFlag = 4;</code>
     */
    public Builder clearUsrStatusFlag() {
      if (usrStatusFlagBuilder_ == null) {
        usrStatusFlag_ = null;
        onChanged();
      } else {
        usrStatusFlag_ = null;
        usrStatusFlagBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 用户账号标识
     * </pre>
     *
     * <code>.UsrStatusFlag usrStatusFlag = 4;</code>
     */
    public com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag.Builder getUsrStatusFlagBuilder() {
      
      onChanged();
      return getUsrStatusFlagFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 用户账号标识
     * </pre>
     *
     * <code>.UsrStatusFlag usrStatusFlag = 4;</code>
     */
    public com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlagOrBuilder getUsrStatusFlagOrBuilder() {
      if (usrStatusFlagBuilder_ != null) {
        return usrStatusFlagBuilder_.getMessageOrBuilder();
      } else {
        return usrStatusFlag_ == null ?
            com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag.getDefaultInstance() : usrStatusFlag_;
      }
    }
    /**
     * <pre>
     * 用户账号标识
     * </pre>
     *
     * <code>.UsrStatusFlag usrStatusFlag = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag, com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag.Builder, com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlagOrBuilder> 
        getUsrStatusFlagFieldBuilder() {
      if (usrStatusFlagBuilder_ == null) {
        usrStatusFlagBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag, com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag.Builder, com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlagOrBuilder>(
                getUsrStatusFlag(),
                getParentForChildren(),
                isClean());
        usrStatusFlag_ = null;
      }
      return usrStatusFlagBuilder_;
    }

    private com.upuphub.dew.community.connection.protobuf.account.LastLoginInfo lastLoginInfo_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.upuphub.dew.community.connection.protobuf.account.LastLoginInfo, com.upuphub.dew.community.connection.protobuf.account.LastLoginInfo.Builder, com.upuphub.dew.community.connection.protobuf.account.LastLoginInfoOrBuilder> lastLoginInfoBuilder_;
    /**
     * <pre>
     * 用户最后登录信息
     * </pre>
     *
     * <code>.LastLoginInfo lastLoginInfo = 5;</code>
     */
    public boolean hasLastLoginInfo() {
      return lastLoginInfoBuilder_ != null || lastLoginInfo_ != null;
    }
    /**
     * <pre>
     * 用户最后登录信息
     * </pre>
     *
     * <code>.LastLoginInfo lastLoginInfo = 5;</code>
     */
    public com.upuphub.dew.community.connection.protobuf.account.LastLoginInfo getLastLoginInfo() {
      if (lastLoginInfoBuilder_ == null) {
        return lastLoginInfo_ == null ? com.upuphub.dew.community.connection.protobuf.account.LastLoginInfo.getDefaultInstance() : lastLoginInfo_;
      } else {
        return lastLoginInfoBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 用户最后登录信息
     * </pre>
     *
     * <code>.LastLoginInfo lastLoginInfo = 5;</code>
     */
    public Builder setLastLoginInfo(com.upuphub.dew.community.connection.protobuf.account.LastLoginInfo value) {
      if (lastLoginInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        lastLoginInfo_ = value;
        onChanged();
      } else {
        lastLoginInfoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 用户最后登录信息
     * </pre>
     *
     * <code>.LastLoginInfo lastLoginInfo = 5;</code>
     */
    public Builder setLastLoginInfo(
        com.upuphub.dew.community.connection.protobuf.account.LastLoginInfo.Builder builderForValue) {
      if (lastLoginInfoBuilder_ == null) {
        lastLoginInfo_ = builderForValue.build();
        onChanged();
      } else {
        lastLoginInfoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 用户最后登录信息
     * </pre>
     *
     * <code>.LastLoginInfo lastLoginInfo = 5;</code>
     */
    public Builder mergeLastLoginInfo(com.upuphub.dew.community.connection.protobuf.account.LastLoginInfo value) {
      if (lastLoginInfoBuilder_ == null) {
        if (lastLoginInfo_ != null) {
          lastLoginInfo_ =
            com.upuphub.dew.community.connection.protobuf.account.LastLoginInfo.newBuilder(lastLoginInfo_).mergeFrom(value).buildPartial();
        } else {
          lastLoginInfo_ = value;
        }
        onChanged();
      } else {
        lastLoginInfoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 用户最后登录信息
     * </pre>
     *
     * <code>.LastLoginInfo lastLoginInfo = 5;</code>
     */
    public Builder clearLastLoginInfo() {
      if (lastLoginInfoBuilder_ == null) {
        lastLoginInfo_ = null;
        onChanged();
      } else {
        lastLoginInfo_ = null;
        lastLoginInfoBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 用户最后登录信息
     * </pre>
     *
     * <code>.LastLoginInfo lastLoginInfo = 5;</code>
     */
    public com.upuphub.dew.community.connection.protobuf.account.LastLoginInfo.Builder getLastLoginInfoBuilder() {
      
      onChanged();
      return getLastLoginInfoFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 用户最后登录信息
     * </pre>
     *
     * <code>.LastLoginInfo lastLoginInfo = 5;</code>
     */
    public com.upuphub.dew.community.connection.protobuf.account.LastLoginInfoOrBuilder getLastLoginInfoOrBuilder() {
      if (lastLoginInfoBuilder_ != null) {
        return lastLoginInfoBuilder_.getMessageOrBuilder();
      } else {
        return lastLoginInfo_ == null ?
            com.upuphub.dew.community.connection.protobuf.account.LastLoginInfo.getDefaultInstance() : lastLoginInfo_;
      }
    }
    /**
     * <pre>
     * 用户最后登录信息
     * </pre>
     *
     * <code>.LastLoginInfo lastLoginInfo = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.upuphub.dew.community.connection.protobuf.account.LastLoginInfo, com.upuphub.dew.community.connection.protobuf.account.LastLoginInfo.Builder, com.upuphub.dew.community.connection.protobuf.account.LastLoginInfoOrBuilder> 
        getLastLoginInfoFieldBuilder() {
      if (lastLoginInfoBuilder_ == null) {
        lastLoginInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.upuphub.dew.community.connection.protobuf.account.LastLoginInfo, com.upuphub.dew.community.connection.protobuf.account.LastLoginInfo.Builder, com.upuphub.dew.community.connection.protobuf.account.LastLoginInfoOrBuilder>(
                getLastLoginInfo(),
                getParentForChildren(),
                isClean());
        lastLoginInfo_ = null;
      }
      return lastLoginInfoBuilder_;
    }

    private int errorCode_ ;
    /**
     * <pre>
     * 请求错误码
     * </pre>
     *
     * <code>int32 errorCode = 6;</code>
     */
    public int getErrorCode() {
      return errorCode_;
    }
    /**
     * <pre>
     * 请求错误码
     * </pre>
     *
     * <code>int32 errorCode = 6;</code>
     */
    public Builder setErrorCode(int value) {
      
      errorCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 请求错误码
     * </pre>
     *
     * <code>int32 errorCode = 6;</code>
     */
    public Builder clearErrorCode() {
      
      errorCode_ = 0;
      onChanged();
      return this;
    }

    private int profileCompletion_ ;
    /**
     * <pre>
     * 信息完成度
     * </pre>
     *
     * <code>int32 profileCompletion = 7;</code>
     */
    public int getProfileCompletion() {
      return profileCompletion_;
    }
    /**
     * <pre>
     * 信息完成度
     * </pre>
     *
     * <code>int32 profileCompletion = 7;</code>
     */
    public Builder setProfileCompletion(int value) {
      
      profileCompletion_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 信息完成度
     * </pre>
     *
     * <code>int32 profileCompletion = 7;</code>
     */
    public Builder clearProfileCompletion() {
      
      profileCompletion_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Profile)
  }

  // @@protoc_insertion_point(class_scope:Profile)
  private static final com.upuphub.dew.community.connection.protobuf.account.Profile DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.upuphub.dew.community.connection.protobuf.account.Profile();
  }

  public static com.upuphub.dew.community.connection.protobuf.account.Profile getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Profile>
      PARSER = new com.google.protobuf.AbstractParser<Profile>() {
    @java.lang.Override
    public Profile parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Profile(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Profile> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Profile> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.upuphub.dew.community.connection.protobuf.account.Profile getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

