// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

package com.upuphub.dew.community.connection.protobuf.account;

public interface ProfileFilterCondOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProfileFilterCond)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 通用Profile的uin
   * </pre>
   *
   * <code>int64 uin = 1;</code>
   */
  long getUin();

  /**
   * <pre>
   * 通用Profile的具体信息
   * </pre>
   *
   * <code>repeated string keys = 2;</code>
   */
  java.util.List<java.lang.String>
      getKeysList();
  /**
   * <pre>
   * 通用Profile的具体信息
   * </pre>
   *
   * <code>repeated string keys = 2;</code>
   */
  int getKeysCount();
  /**
   * <pre>
   * 通用Profile的具体信息
   * </pre>
   *
   * <code>repeated string keys = 2;</code>
   */
  java.lang.String getKeys(int index);
  /**
   * <pre>
   * 通用Profile的具体信息
   * </pre>
   *
   * <code>repeated string keys = 2;</code>
   */
  com.google.protobuf.ByteString
      getKeysBytes(int index);
}
