// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

package com.upuphub.dew.community.connection.protobuf.account;

/**
 * Protobuf type {@code ProfileFilterCond}
 */
public  final class ProfileFilterCond extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ProfileFilterCond)
    ProfileFilterCondOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ProfileFilterCond.newBuilder() to construct.
  private ProfileFilterCond(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProfileFilterCond() {
    keys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ProfileFilterCond();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ProfileFilterCond(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            uin_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              keys_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            keys_.add(s);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        keys_ = keys_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.upuphub.dew.community.connection.protobuf.account.Account.internal_static_ProfileFilterCond_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.upuphub.dew.community.connection.protobuf.account.Account.internal_static_ProfileFilterCond_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.upuphub.dew.community.connection.protobuf.account.ProfileFilterCond.class, com.upuphub.dew.community.connection.protobuf.account.ProfileFilterCond.Builder.class);
  }

  public static final int UIN_FIELD_NUMBER = 1;
  private long uin_;
  /**
   * <pre>
   * 通用Profile的uin
   * </pre>
   *
   * <code>int64 uin = 1;</code>
   */
  public long getUin() {
    return uin_;
  }

  public static final int KEYS_FIELD_NUMBER = 2;
  private com.google.protobuf.LazyStringList keys_;
  /**
   * <pre>
   * 通用Profile的具体信息
   * </pre>
   *
   * <code>repeated string keys = 2;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getKeysList() {
    return keys_;
  }
  /**
   * <pre>
   * 通用Profile的具体信息
   * </pre>
   *
   * <code>repeated string keys = 2;</code>
   */
  public int getKeysCount() {
    return keys_.size();
  }
  /**
   * <pre>
   * 通用Profile的具体信息
   * </pre>
   *
   * <code>repeated string keys = 2;</code>
   */
  public java.lang.String getKeys(int index) {
    return keys_.get(index);
  }
  /**
   * <pre>
   * 通用Profile的具体信息
   * </pre>
   *
   * <code>repeated string keys = 2;</code>
   */
  public com.google.protobuf.ByteString
      getKeysBytes(int index) {
    return keys_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (uin_ != 0L) {
      output.writeInt64(1, uin_);
    }
    for (int i = 0; i < keys_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, keys_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (uin_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, uin_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < keys_.size(); i++) {
        dataSize += computeStringSizeNoTag(keys_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getKeysList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.upuphub.dew.community.connection.protobuf.account.ProfileFilterCond)) {
      return super.equals(obj);
    }
    com.upuphub.dew.community.connection.protobuf.account.ProfileFilterCond other = (com.upuphub.dew.community.connection.protobuf.account.ProfileFilterCond) obj;

    if (getUin()
        != other.getUin()) return false;
    if (!getKeysList()
        .equals(other.getKeysList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + UIN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUin());
    if (getKeysCount() > 0) {
      hash = (37 * hash) + KEYS_FIELD_NUMBER;
      hash = (53 * hash) + getKeysList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.upuphub.dew.community.connection.protobuf.account.ProfileFilterCond parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.upuphub.dew.community.connection.protobuf.account.ProfileFilterCond parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.upuphub.dew.community.connection.protobuf.account.ProfileFilterCond parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.upuphub.dew.community.connection.protobuf.account.ProfileFilterCond parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.upuphub.dew.community.connection.protobuf.account.ProfileFilterCond parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.upuphub.dew.community.connection.protobuf.account.ProfileFilterCond parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.upuphub.dew.community.connection.protobuf.account.ProfileFilterCond parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.upuphub.dew.community.connection.protobuf.account.ProfileFilterCond parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.upuphub.dew.community.connection.protobuf.account.ProfileFilterCond parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.upuphub.dew.community.connection.protobuf.account.ProfileFilterCond parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.upuphub.dew.community.connection.protobuf.account.ProfileFilterCond parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.upuphub.dew.community.connection.protobuf.account.ProfileFilterCond parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.upuphub.dew.community.connection.protobuf.account.ProfileFilterCond prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ProfileFilterCond}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ProfileFilterCond)
      com.upuphub.dew.community.connection.protobuf.account.ProfileFilterCondOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.upuphub.dew.community.connection.protobuf.account.Account.internal_static_ProfileFilterCond_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.upuphub.dew.community.connection.protobuf.account.Account.internal_static_ProfileFilterCond_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.upuphub.dew.community.connection.protobuf.account.ProfileFilterCond.class, com.upuphub.dew.community.connection.protobuf.account.ProfileFilterCond.Builder.class);
    }

    // Construct using com.upuphub.dew.community.connection.protobuf.account.ProfileFilterCond.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      uin_ = 0L;

      keys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.upuphub.dew.community.connection.protobuf.account.Account.internal_static_ProfileFilterCond_descriptor;
    }

    @java.lang.Override
    public com.upuphub.dew.community.connection.protobuf.account.ProfileFilterCond getDefaultInstanceForType() {
      return com.upuphub.dew.community.connection.protobuf.account.ProfileFilterCond.getDefaultInstance();
    }

    @java.lang.Override
    public com.upuphub.dew.community.connection.protobuf.account.ProfileFilterCond build() {
      com.upuphub.dew.community.connection.protobuf.account.ProfileFilterCond result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.upuphub.dew.community.connection.protobuf.account.ProfileFilterCond buildPartial() {
      com.upuphub.dew.community.connection.protobuf.account.ProfileFilterCond result = new com.upuphub.dew.community.connection.protobuf.account.ProfileFilterCond(this);
      int from_bitField0_ = bitField0_;
      result.uin_ = uin_;
      if (((bitField0_ & 0x00000001) != 0)) {
        keys_ = keys_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.keys_ = keys_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.upuphub.dew.community.connection.protobuf.account.ProfileFilterCond) {
        return mergeFrom((com.upuphub.dew.community.connection.protobuf.account.ProfileFilterCond)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.upuphub.dew.community.connection.protobuf.account.ProfileFilterCond other) {
      if (other == com.upuphub.dew.community.connection.protobuf.account.ProfileFilterCond.getDefaultInstance()) return this;
      if (other.getUin() != 0L) {
        setUin(other.getUin());
      }
      if (!other.keys_.isEmpty()) {
        if (keys_.isEmpty()) {
          keys_ = other.keys_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureKeysIsMutable();
          keys_.addAll(other.keys_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.upuphub.dew.community.connection.protobuf.account.ProfileFilterCond parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.upuphub.dew.community.connection.protobuf.account.ProfileFilterCond) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long uin_ ;
    /**
     * <pre>
     * 通用Profile的uin
     * </pre>
     *
     * <code>int64 uin = 1;</code>
     */
    public long getUin() {
      return uin_;
    }
    /**
     * <pre>
     * 通用Profile的uin
     * </pre>
     *
     * <code>int64 uin = 1;</code>
     */
    public Builder setUin(long value) {
      
      uin_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 通用Profile的uin
     * </pre>
     *
     * <code>int64 uin = 1;</code>
     */
    public Builder clearUin() {
      
      uin_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList keys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureKeysIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        keys_ = new com.google.protobuf.LazyStringArrayList(keys_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <pre>
     * 通用Profile的具体信息
     * </pre>
     *
     * <code>repeated string keys = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getKeysList() {
      return keys_.getUnmodifiableView();
    }
    /**
     * <pre>
     * 通用Profile的具体信息
     * </pre>
     *
     * <code>repeated string keys = 2;</code>
     */
    public int getKeysCount() {
      return keys_.size();
    }
    /**
     * <pre>
     * 通用Profile的具体信息
     * </pre>
     *
     * <code>repeated string keys = 2;</code>
     */
    public java.lang.String getKeys(int index) {
      return keys_.get(index);
    }
    /**
     * <pre>
     * 通用Profile的具体信息
     * </pre>
     *
     * <code>repeated string keys = 2;</code>
     */
    public com.google.protobuf.ByteString
        getKeysBytes(int index) {
      return keys_.getByteString(index);
    }
    /**
     * <pre>
     * 通用Profile的具体信息
     * </pre>
     *
     * <code>repeated string keys = 2;</code>
     */
    public Builder setKeys(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureKeysIsMutable();
      keys_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 通用Profile的具体信息
     * </pre>
     *
     * <code>repeated string keys = 2;</code>
     */
    public Builder addKeys(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureKeysIsMutable();
      keys_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 通用Profile的具体信息
     * </pre>
     *
     * <code>repeated string keys = 2;</code>
     */
    public Builder addAllKeys(
        java.lang.Iterable<java.lang.String> values) {
      ensureKeysIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, keys_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 通用Profile的具体信息
     * </pre>
     *
     * <code>repeated string keys = 2;</code>
     */
    public Builder clearKeys() {
      keys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 通用Profile的具体信息
     * </pre>
     *
     * <code>repeated string keys = 2;</code>
     */
    public Builder addKeysBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureKeysIsMutable();
      keys_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ProfileFilterCond)
  }

  // @@protoc_insertion_point(class_scope:ProfileFilterCond)
  private static final com.upuphub.dew.community.connection.protobuf.account.ProfileFilterCond DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.upuphub.dew.community.connection.protobuf.account.ProfileFilterCond();
  }

  public static com.upuphub.dew.community.connection.protobuf.account.ProfileFilterCond getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProfileFilterCond>
      PARSER = new com.google.protobuf.AbstractParser<ProfileFilterCond>() {
    @java.lang.Override
    public ProfileFilterCond parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ProfileFilterCond(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ProfileFilterCond> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProfileFilterCond> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.upuphub.dew.community.connection.protobuf.account.ProfileFilterCond getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

