// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

package com.upuphub.dew.community.connection.protobuf.account;

public interface ResetPasswordOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ResetPassword)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 重置用户密码的Uin
   * </pre>
   *
   * <code>int64 uin = 1;</code>
   */
  long getUin();

  /**
   * <pre>
   * 用户邮箱
   * </pre>
   *
   * <code>string email = 2;</code>
   */
  java.lang.String getEmail();
  /**
   * <pre>
   * 用户邮箱
   * </pre>
   *
   * <code>string email = 2;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <pre>
   * 需要重置的用户新密码
   * </pre>
   *
   * <code>string password = 3;</code>
   */
  java.lang.String getPassword();
  /**
   * <pre>
   * 需要重置的用户新密码
   * </pre>
   *
   * <code>string password = 3;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
