// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

package com.upuphub.dew.community.connection.protobuf.account;

public interface UsernameAndPasswordOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UsernameAndPassword)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 用户名
   * </pre>
   *
   * <code>string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <pre>
   * 用户名
   * </pre>
   *
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <pre>
   * 密码
   * </pre>
   *
   * <code>string password = 2;</code>
   */
  java.lang.String getPassword();
  /**
   * <pre>
   * 密码
   * </pre>
   *
   * <code>string password = 2;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <pre>
   * 设备信息
   * </pre>
   *
   * <code>.UsernameAndPassword.Device device = 3;</code>
   */
  boolean hasDevice();
  /**
   * <pre>
   * 设备信息
   * </pre>
   *
   * <code>.UsernameAndPassword.Device device = 3;</code>
   */
  com.upuphub.dew.community.connection.protobuf.account.UsernameAndPassword.Device getDevice();
  /**
   * <pre>
   * 设备信息
   * </pre>
   *
   * <code>.UsernameAndPassword.Device device = 3;</code>
   */
  com.upuphub.dew.community.connection.protobuf.account.UsernameAndPassword.DeviceOrBuilder getDeviceOrBuilder();

  /**
   * <code>int32 idType = 4;</code>
   */
  int getIdType();
}
