// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

package com.upuphub.dew.community.connection.protobuf.account;

public interface UsrProfileOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UsrProfile)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 用户名
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   * 用户名
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * 用户头像
   * </pre>
   *
   * <code>string avatar = 2;</code>
   */
  java.lang.String getAvatar();
  /**
   * <pre>
   * 用户头像
   * </pre>
   *
   * <code>string avatar = 2;</code>
   */
  com.google.protobuf.ByteString
      getAvatarBytes();

  /**
   * <pre>
   * 用户所在国家
   * </pre>
   *
   * <code>string country = 3;</code>
   */
  java.lang.String getCountry();
  /**
   * <pre>
   * 用户所在国家
   * </pre>
   *
   * <code>string country = 3;</code>
   */
  com.google.protobuf.ByteString
      getCountryBytes();

  /**
   * <pre>
   * 用户所在省份
   * </pre>
   *
   * <code>string province = 4;</code>
   */
  java.lang.String getProvince();
  /**
   * <pre>
   * 用户所在省份
   * </pre>
   *
   * <code>string province = 4;</code>
   */
  com.google.protobuf.ByteString
      getProvinceBytes();

  /**
   * <pre>
   * 用户所在城市
   * </pre>
   *
   * <code>string city = 5;</code>
   */
  java.lang.String getCity();
  /**
   * <pre>
   * 用户所在城市
   * </pre>
   *
   * <code>string city = 5;</code>
   */
  com.google.protobuf.ByteString
      getCityBytes();

  /**
   * <pre>
   * 县/区
   * </pre>
   *
   * <code>string district = 6;</code>
   */
  java.lang.String getDistrict();
  /**
   * <pre>
   * 县/区
   * </pre>
   *
   * <code>string district = 6;</code>
   */
  com.google.protobuf.ByteString
      getDistrictBytes();

  /**
   * <pre>
   * 用户所在街道
   * </pre>
   *
   * <code>string street = 7;</code>
   */
  java.lang.String getStreet();
  /**
   * <pre>
   * 用户所在街道
   * </pre>
   *
   * <code>string street = 7;</code>
   */
  com.google.protobuf.ByteString
      getStreetBytes();

  /**
   * <pre>
   * 用户生日
   * </pre>
   *
   * <code>int64 birthday = 8;</code>
   */
  long getBirthday();

  /**
   * <pre>
   * 用户年龄
   * </pre>
   *
   * <code>int32 age = 9;</code>
   */
  int getAge();

  /**
   * <pre>
   * 用户职业
   * </pre>
   *
   * <code>string profession = 10;</code>
   */
  java.lang.String getProfession();
  /**
   * <pre>
   * 用户职业
   * </pre>
   *
   * <code>string profession = 10;</code>
   */
  com.google.protobuf.ByteString
      getProfessionBytes();

  /**
   * <pre>
   * 用户性别
   * </pre>
   *
   * <code>string gender = 11;</code>
   */
  java.lang.String getGender();
  /**
   * <pre>
   * 用户性别
   * </pre>
   *
   * <code>string gender = 11;</code>
   */
  com.google.protobuf.ByteString
      getGenderBytes();

  /**
   * <pre>
   * 用户宣言
   * </pre>
   *
   * <code>string signature = 12;</code>
   */
  java.lang.String getSignature();
  /**
   * <pre>
   * 用户宣言
   * </pre>
   *
   * <code>string signature = 12;</code>
   */
  com.google.protobuf.ByteString
      getSignatureBytes();

  /**
   * <pre>
   * 用户等级
   * </pre>
   *
   * <code>int32 level = 13;</code>
   */
  int getLevel();

  /**
   * <pre>
   * 关于我
   * </pre>
   *
   * <code>string aboutMe = 14;</code>
   */
  java.lang.String getAboutMe();
  /**
   * <pre>
   * 关于我
   * </pre>
   *
   * <code>string aboutMe = 14;</code>
   */
  com.google.protobuf.ByteString
      getAboutMeBytes();

  /**
   * <pre>
   * 用户学校
   * </pre>
   *
   * <code>string school = 15;</code>
   */
  java.lang.String getSchool();
  /**
   * <pre>
   * 用户学校
   * </pre>
   *
   * <code>string school = 15;</code>
   */
  com.google.protobuf.ByteString
      getSchoolBytes();

  /**
   * <pre>
   * 用户公司
   * </pre>
   *
   * <code>string company = 16;</code>
   */
  java.lang.String getCompany();
  /**
   * <pre>
   * 用户公司
   * </pre>
   *
   * <code>string company = 16;</code>
   */
  com.google.protobuf.ByteString
      getCompanyBytes();

  /**
   * <pre>
   * 用户教育水平
   * </pre>
   *
   * <code>string degree = 17;</code>
   */
  java.lang.String getDegree();
  /**
   * <pre>
   * 用户教育水平
   * </pre>
   *
   * <code>string degree = 17;</code>
   */
  com.google.protobuf.ByteString
      getDegreeBytes();

  /**
   * <pre>
   * 用户使用语言
   * </pre>
   *
   * <code>string language = 18;</code>
   */
  java.lang.String getLanguage();
  /**
   * <pre>
   * 用户使用语言
   * </pre>
   *
   * <code>string language = 18;</code>
   */
  com.google.protobuf.ByteString
      getLanguageBytes();

  /**
   * <pre>
   * 用户信息背景图像
   * </pre>
   *
   * <code>string backgroundImage = 19;</code>
   */
  java.lang.String getBackgroundImage();
  /**
   * <pre>
   * 用户信息背景图像
   * </pre>
   *
   * <code>string backgroundImage = 19;</code>
   */
  com.google.protobuf.ByteString
      getBackgroundImageBytes();
}
