// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

package com.upuphub.dew.community.connection.protobuf.account;

/**
 * Protobuf type {@code UsrStatusFlag}
 */
public  final class UsrStatusFlag extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:UsrStatusFlag)
    UsrStatusFlagOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UsrStatusFlag.newBuilder() to construct.
  private UsrStatusFlag(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UsrStatusFlag() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UsrStatusFlag();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UsrStatusFlag(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            emailVerifiedFlag_ = input.readBool();
            break;
          }
          case 16: {

            disableFlag_ = input.readBool();
            break;
          }
          case 24: {

            needMoreInfoFlag_ = input.readBool();
            break;
          }
          case 32: {

            completelyRegistrationFlag_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.upuphub.dew.community.connection.protobuf.account.Account.internal_static_UsrStatusFlag_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.upuphub.dew.community.connection.protobuf.account.Account.internal_static_UsrStatusFlag_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag.class, com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag.Builder.class);
  }

  public static final int EMAILVERIFIEDFLAG_FIELD_NUMBER = 1;
  private boolean emailVerifiedFlag_;
  /**
   * <pre>
   * 用户邮箱验证状态
   * </pre>
   *
   * <code>bool emailVerifiedFlag = 1;</code>
   */
  public boolean getEmailVerifiedFlag() {
    return emailVerifiedFlag_;
  }

  public static final int DISABLEFLAG_FIELD_NUMBER = 2;
  private boolean disableFlag_;
  /**
   * <pre>
   * 用户可使用验证状态
   * </pre>
   *
   * <code>bool disableFlag = 2;</code>
   */
  public boolean getDisableFlag() {
    return disableFlag_;
  }

  public static final int NEEDMOREINFOFLAG_FIELD_NUMBER = 3;
  private boolean needMoreInfoFlag_;
  /**
   * <pre>
   * 需要用户完善信息
   * </pre>
   *
   * <code>bool needMoreInfoFlag = 3;</code>
   */
  public boolean getNeedMoreInfoFlag() {
    return needMoreInfoFlag_;
  }

  public static final int COMPLETELYREGISTRATIONFLAG_FIELD_NUMBER = 4;
  private boolean completelyRegistrationFlag_;
  /**
   * <pre>
   * 完成注册标记
   * </pre>
   *
   * <code>bool completelyRegistrationFlag = 4;</code>
   */
  public boolean getCompletelyRegistrationFlag() {
    return completelyRegistrationFlag_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (emailVerifiedFlag_ != false) {
      output.writeBool(1, emailVerifiedFlag_);
    }
    if (disableFlag_ != false) {
      output.writeBool(2, disableFlag_);
    }
    if (needMoreInfoFlag_ != false) {
      output.writeBool(3, needMoreInfoFlag_);
    }
    if (completelyRegistrationFlag_ != false) {
      output.writeBool(4, completelyRegistrationFlag_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (emailVerifiedFlag_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, emailVerifiedFlag_);
    }
    if (disableFlag_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, disableFlag_);
    }
    if (needMoreInfoFlag_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, needMoreInfoFlag_);
    }
    if (completelyRegistrationFlag_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, completelyRegistrationFlag_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag)) {
      return super.equals(obj);
    }
    com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag other = (com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag) obj;

    if (getEmailVerifiedFlag()
        != other.getEmailVerifiedFlag()) return false;
    if (getDisableFlag()
        != other.getDisableFlag()) return false;
    if (getNeedMoreInfoFlag()
        != other.getNeedMoreInfoFlag()) return false;
    if (getCompletelyRegistrationFlag()
        != other.getCompletelyRegistrationFlag()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EMAILVERIFIEDFLAG_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getEmailVerifiedFlag());
    hash = (37 * hash) + DISABLEFLAG_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getDisableFlag());
    hash = (37 * hash) + NEEDMOREINFOFLAG_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getNeedMoreInfoFlag());
    hash = (37 * hash) + COMPLETELYREGISTRATIONFLAG_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getCompletelyRegistrationFlag());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code UsrStatusFlag}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:UsrStatusFlag)
      com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlagOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.upuphub.dew.community.connection.protobuf.account.Account.internal_static_UsrStatusFlag_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.upuphub.dew.community.connection.protobuf.account.Account.internal_static_UsrStatusFlag_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag.class, com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag.Builder.class);
    }

    // Construct using com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      emailVerifiedFlag_ = false;

      disableFlag_ = false;

      needMoreInfoFlag_ = false;

      completelyRegistrationFlag_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.upuphub.dew.community.connection.protobuf.account.Account.internal_static_UsrStatusFlag_descriptor;
    }

    @java.lang.Override
    public com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag getDefaultInstanceForType() {
      return com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag.getDefaultInstance();
    }

    @java.lang.Override
    public com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag build() {
      com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag buildPartial() {
      com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag result = new com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag(this);
      result.emailVerifiedFlag_ = emailVerifiedFlag_;
      result.disableFlag_ = disableFlag_;
      result.needMoreInfoFlag_ = needMoreInfoFlag_;
      result.completelyRegistrationFlag_ = completelyRegistrationFlag_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag) {
        return mergeFrom((com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag other) {
      if (other == com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag.getDefaultInstance()) return this;
      if (other.getEmailVerifiedFlag() != false) {
        setEmailVerifiedFlag(other.getEmailVerifiedFlag());
      }
      if (other.getDisableFlag() != false) {
        setDisableFlag(other.getDisableFlag());
      }
      if (other.getNeedMoreInfoFlag() != false) {
        setNeedMoreInfoFlag(other.getNeedMoreInfoFlag());
      }
      if (other.getCompletelyRegistrationFlag() != false) {
        setCompletelyRegistrationFlag(other.getCompletelyRegistrationFlag());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean emailVerifiedFlag_ ;
    /**
     * <pre>
     * 用户邮箱验证状态
     * </pre>
     *
     * <code>bool emailVerifiedFlag = 1;</code>
     */
    public boolean getEmailVerifiedFlag() {
      return emailVerifiedFlag_;
    }
    /**
     * <pre>
     * 用户邮箱验证状态
     * </pre>
     *
     * <code>bool emailVerifiedFlag = 1;</code>
     */
    public Builder setEmailVerifiedFlag(boolean value) {
      
      emailVerifiedFlag_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户邮箱验证状态
     * </pre>
     *
     * <code>bool emailVerifiedFlag = 1;</code>
     */
    public Builder clearEmailVerifiedFlag() {
      
      emailVerifiedFlag_ = false;
      onChanged();
      return this;
    }

    private boolean disableFlag_ ;
    /**
     * <pre>
     * 用户可使用验证状态
     * </pre>
     *
     * <code>bool disableFlag = 2;</code>
     */
    public boolean getDisableFlag() {
      return disableFlag_;
    }
    /**
     * <pre>
     * 用户可使用验证状态
     * </pre>
     *
     * <code>bool disableFlag = 2;</code>
     */
    public Builder setDisableFlag(boolean value) {
      
      disableFlag_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户可使用验证状态
     * </pre>
     *
     * <code>bool disableFlag = 2;</code>
     */
    public Builder clearDisableFlag() {
      
      disableFlag_ = false;
      onChanged();
      return this;
    }

    private boolean needMoreInfoFlag_ ;
    /**
     * <pre>
     * 需要用户完善信息
     * </pre>
     *
     * <code>bool needMoreInfoFlag = 3;</code>
     */
    public boolean getNeedMoreInfoFlag() {
      return needMoreInfoFlag_;
    }
    /**
     * <pre>
     * 需要用户完善信息
     * </pre>
     *
     * <code>bool needMoreInfoFlag = 3;</code>
     */
    public Builder setNeedMoreInfoFlag(boolean value) {
      
      needMoreInfoFlag_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 需要用户完善信息
     * </pre>
     *
     * <code>bool needMoreInfoFlag = 3;</code>
     */
    public Builder clearNeedMoreInfoFlag() {
      
      needMoreInfoFlag_ = false;
      onChanged();
      return this;
    }

    private boolean completelyRegistrationFlag_ ;
    /**
     * <pre>
     * 完成注册标记
     * </pre>
     *
     * <code>bool completelyRegistrationFlag = 4;</code>
     */
    public boolean getCompletelyRegistrationFlag() {
      return completelyRegistrationFlag_;
    }
    /**
     * <pre>
     * 完成注册标记
     * </pre>
     *
     * <code>bool completelyRegistrationFlag = 4;</code>
     */
    public Builder setCompletelyRegistrationFlag(boolean value) {
      
      completelyRegistrationFlag_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 完成注册标记
     * </pre>
     *
     * <code>bool completelyRegistrationFlag = 4;</code>
     */
    public Builder clearCompletelyRegistrationFlag() {
      
      completelyRegistrationFlag_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:UsrStatusFlag)
  }

  // @@protoc_insertion_point(class_scope:UsrStatusFlag)
  private static final com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag();
  }

  public static com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UsrStatusFlag>
      PARSER = new com.google.protobuf.AbstractParser<UsrStatusFlag>() {
    @java.lang.Override
    public UsrStatusFlag parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UsrStatusFlag(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UsrStatusFlag> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UsrStatusFlag> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.upuphub.dew.community.connection.protobuf.account.UsrStatusFlag getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

