// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

package com.upuphub.dew.community.connection.protobuf.account;

public interface UsrStatusFlagOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UsrStatusFlag)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 用户邮箱验证状态
   * </pre>
   *
   * <code>bool emailVerifiedFlag = 1;</code>
   */
  boolean getEmailVerifiedFlag();

  /**
   * <pre>
   * 用户可使用验证状态
   * </pre>
   *
   * <code>bool disableFlag = 2;</code>
   */
  boolean getDisableFlag();

  /**
   * <pre>
   * 需要用户完善信息
   * </pre>
   *
   * <code>bool needMoreInfoFlag = 3;</code>
   */
  boolean getNeedMoreInfoFlag();

  /**
   * <pre>
   * 完成注册标记
   * </pre>
   *
   * <code>bool completelyRegistrationFlag = 4;</code>
   */
  boolean getCompletelyRegistrationFlag();
}
