server:
  port: 9687


spring:
  application:
    name: dew-smart-community-message
  cloud:
      # SpringCloud-Alibaba-Nacos服务注册中心配置
    nacos:
      discovery:
        ip: 10.147.20.215
        server-addr: support.upuphub.com:8848
  data:
    # mongodb数据库-服务配置
    mongodb:
      host: 10.147.20.20
      database: dew_message
      password: A!@#456bnm
      port: 37017
      username: dewmsg
dew:
  data-center-id: 1
  work-id: 1
  mqtt:
    username: DewMessageProducer
    password: DewMessageProducer
    # 推送信息的连接地址，如果有多个，用逗号隔开，如：tcp://127.0.0.1:61613,tcp://192.168.1.61:616
    url: tcp://support.upuphub.com:6788
    producer:
      # 连接服务器默认客户端ID
      clientId: DewMessageProducer
      # 默认的推送主题，实际可在调用接口时指定
      defaultTopic: DEW_MESSAGE


logging:
  level:
    root: debug

##################
#  MQTT 配置
##################

management:
  endpoints:
    web:
      exposure:
        include: "*"