// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: push.proto

package com.upuphub.dew.community.connection.protobuf.push;

public interface EmailAndCodeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EmailAndCode)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string code = 1;</code>
   */
  java.lang.String getCode();
  /**
   * <code>string code = 1;</code>
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>string email = 2;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 2;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();
}
