// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: push.proto

package com.upuphub.dew.community.connection.protobuf.push;

public final class Push {
  private Push() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmailAndCode_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmailAndCode_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\npush.proto\"+\n\014EmailAndCode\022\014\n\004code\030\001 \001" +
      "(\t\022\r\n\005email\030\002 \001(\tB6\n2com.upuphub.dew.com" +
      "munity.connection.protobuf.pushP\001b\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_EmailAndCode_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_EmailAndCode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmailAndCode_descriptor,
        new java.lang.String[] { "Code", "Email", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
