// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: moments.proto

package com.upuphub.dew.community.connection.protobuf.moments;

public interface DynamicIdResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DynamicIdResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Dynamic Content ID
   * </pre>
   *
   * <code>int64 dynamicId = 1;</code>
   */
  long getDynamicId();
}
