// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: moments.proto

package com.upuphub.dew.community.connection.protobuf.moments;

public interface DynamicContentCellOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DynamicContentCell)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 用户动态消息的ID
   * </pre>
   *
   * <code>int64 dynamicContentId = 1;</code>
   */
  long getDynamicContentId();

  /**
   * <pre>
   * 用户发布消息的经度
   * </pre>
   *
   * <code>double longitude = 2;</code>
   */
  double getLongitude();

  /**
   * <pre>
   * 用户发布消息的维度
   * </pre>
   *
   * <code>double latitude = 3;</code>
   */
  double getLatitude();

  /**
   * <pre>
   * 用户发布消息的消息正文
   * </pre>
   *
   * <code>string dynamic = 4;</code>
   */
  java.lang.String getDynamic();
  /**
   * <pre>
   * 用户发布消息的消息正文
   * </pre>
   *
   * <code>string dynamic = 4;</code>
   */
  com.google.protobuf.ByteString
      getDynamicBytes();

  /**
   * <pre>
   * 用户发布消息携带的配图
   * </pre>
   *
   * <code>repeated string pictures = 5;</code>
   */
  java.util.List<java.lang.String>
      getPicturesList();
  /**
   * <pre>
   * 用户发布消息携带的配图
   * </pre>
   *
   * <code>repeated string pictures = 5;</code>
   */
  int getPicturesCount();
  /**
   * <pre>
   * 用户发布消息携带的配图
   * </pre>
   *
   * <code>repeated string pictures = 5;</code>
   */
  java.lang.String getPictures(int index);
  /**
   * <pre>
   * 用户发布消息携带的配图
   * </pre>
   *
   * <code>repeated string pictures = 5;</code>
   */
  com.google.protobuf.ByteString
      getPicturesBytes(int index);

  /**
   * <pre>
   * 用户动态信息参与的话题
   * </pre>
   *
   * <code>string topic = 6;</code>
   */
  java.lang.String getTopic();
  /**
   * <pre>
   * 用户动态信息参与的话题
   * </pre>
   *
   * <code>string topic = 6;</code>
   */
  com.google.protobuf.ByteString
      getTopicBytes();

  /**
   * <pre>
   * 用户消息动态的种类
   * </pre>
   *
   * <code>int32 classify = 7;</code>
   */
  int getClassify();

  /**
   * <pre>
   * 用户消息动态的更新时间
   * </pre>
   *
   * <code>int64 publishTime = 8;</code>
   */
  long getPublishTime();

  /**
   * <pre>
   * 消息原始Uin
   * </pre>
   *
   * <code>int64 originUin = 9;</code>
   */
  long getOriginUin();

  /**
   * <pre>
   * 动态消息的点赞数量
   * </pre>
   *
   * <code>int64 likeNumber = 10;</code>
   */
  long getLikeNumber();

  /**
   * <pre>
   * 消息的发布类型
   * </pre>
   *
   * <code>.MOMENTS_DYNAMIC_PUBLISH_TYPE publishType = 11;</code>
   */
  int getPublishTypeValue();
  /**
   * <pre>
   * 消息的发布类型
   * </pre>
   *
   * <code>.MOMENTS_DYNAMIC_PUBLISH_TYPE publishType = 11;</code>
   */
  com.upuphub.dew.community.connection.protobuf.moments.MOMENTS_DYNAMIC_PUBLISH_TYPE getPublishType();
}
