// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: moments.proto

package com.upuphub.dew.community.connection.protobuf.moments;

public interface DynamicHistoryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DynamicHistoryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 发布者Uin
   * </pre>
   *
   * <code>int64 founder = 1;</code>
   */
  long getFounder();

  /**
   * <pre>
   * 每页的大小
   * </pre>
   *
   * <code>int32 pageSize = 2;</code>
   */
  int getPageSize();

  /**
   * <pre>
   * 需要的页码数
   * </pre>
   *
   * <code>int32 pageNum = 3;</code>
   */
  int getPageNum();
}
