// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: moments.proto

package com.upuphub.dew.community.connection.protobuf.moments;

public interface DynamicsContentResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DynamicsContentResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 消息发布的时间
   * </pre>
   *
   * <code>repeated .DynamicContentResultCell DynamicContentCells = 1;</code>
   */
  java.util.List<com.upuphub.dew.community.connection.protobuf.moments.DynamicContentResultCell> 
      getDynamicContentCellsList();
  /**
   * <pre>
   * 消息发布的时间
   * </pre>
   *
   * <code>repeated .DynamicContentResultCell DynamicContentCells = 1;</code>
   */
  com.upuphub.dew.community.connection.protobuf.moments.DynamicContentResultCell getDynamicContentCells(int index);
  /**
   * <pre>
   * 消息发布的时间
   * </pre>
   *
   * <code>repeated .DynamicContentResultCell DynamicContentCells = 1;</code>
   */
  int getDynamicContentCellsCount();
  /**
   * <pre>
   * 消息发布的时间
   * </pre>
   *
   * <code>repeated .DynamicContentResultCell DynamicContentCells = 1;</code>
   */
  java.util.List<? extends com.upuphub.dew.community.connection.protobuf.moments.DynamicContentResultCellOrBuilder> 
      getDynamicContentCellsOrBuilderList();
  /**
   * <pre>
   * 消息发布的时间
   * </pre>
   *
   * <code>repeated .DynamicContentResultCell DynamicContentCells = 1;</code>
   */
  com.upuphub.dew.community.connection.protobuf.moments.DynamicContentResultCellOrBuilder getDynamicContentCellsOrBuilder(
      int index);

  /**
   * <pre>
   * 分页信息
   * </pre>
   *
   * <code>.PageInfo pageInfo = 2;</code>
   */
  boolean hasPageInfo();
  /**
   * <pre>
   * 分页信息
   * </pre>
   *
   * <code>.PageInfo pageInfo = 2;</code>
   */
  com.upuphub.dew.community.connection.protobuf.moments.PageInfo getPageInfo();
  /**
   * <pre>
   * 分页信息
   * </pre>
   *
   * <code>.PageInfo pageInfo = 2;</code>
   */
  com.upuphub.dew.community.connection.protobuf.moments.PageInfoOrBuilder getPageInfoOrBuilder();
}
