// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: moments.proto

package com.upuphub.dew.community.connection.protobuf.moments;

public interface FounderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Founder)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 发布者Uin
   * </pre>
   *
   * <code>int64 founder = 1;</code>
   */
  long getFounder();
}
