// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: moments.proto

package com.upuphub.dew.community.connection.protobuf.moments;

public final class Moments {
  private Moments() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MomentDynamicContent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MomentDynamicContent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DynamicContentResultCell_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DynamicContentResultCell_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DynamicsContentResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DynamicsContentResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DynamicHistoryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DynamicHistoryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PageInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PageInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Founder_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Founder_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DynamicIdResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DynamicIdResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MomentDynamicPublish_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MomentDynamicPublish_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmoments.proto\"\272\001\n\024MomentDynamicContent" +
      "\022\013\n\003uin\030\001 \001(\003\022\021\n\tlongitude\030\002 \001(\001\022\020\n\010lati" +
      "tude\030\003 \001(\001\022\017\n\007dynamic\030\004 \001(\t\022\020\n\010pictures\030" +
      "\005 \003(\t\022\r\n\005topic\030\006 \001(\t\022\020\n\010classify\030\007 \001(\005\022\022" +
      "\n\nupdateTime\030\010 \001(\003\022\030\n\020dynamicContentId\030\t" +
      " \001(\003\"\215\002\n\030DynamicContentResultCell\022\030\n\020dyn" +
      "amicContentId\030\001 \001(\003\022\021\n\tlongitude\030\002 \001(\001\022\020" +
      "\n\010latitude\030\003 \001(\001\022\017\n\007dynamic\030\004 \001(\t\022\020\n\010pic" +
      "tures\030\005 \003(\t\022\r\n\005topic\030\006 \001(\t\022\020\n\010classify\030\007" +
      " \001(\005\022\023\n\013publishTime\030\010 \001(\003\022\021\n\toriginUin\030\t" +
      " \001(\003\022\022\n\nlikeNumber\030\n \001(\003\0222\n\013publishType\030" +
      "\013 \001(\0162\035.MOMENTS_DYNAMIC_PUBLISH_TYPE\"l\n\025" +
      "DynamicsContentResult\0226\n\023DynamicContentC" +
      "ells\030\001 \003(\0132\031.DynamicContentResultCell\022\033\n" +
      "\010pageInfo\030\002 \001(\0132\t.PageInfo\"K\n\025DynamicHis" +
      "toryRequest\022\017\n\007founder\030\001 \001(\003\022\020\n\010pageSize" +
      "\030\002 \001(\005\022\017\n\007pageNum\030\003 \001(\005\"\260\001\n\010PageInfo\022\017\n\007" +
      "pageNum\030\001 \001(\005\022\020\n\010pageSize\030\002 \001(\005\022\014\n\004size\030" +
      "\003 \001(\005\022\r\n\005total\030\004 \001(\003\022\r\n\005pages\030\005 \001(\005\022\023\n\013i" +
      "sFirstPage\030\006 \001(\010\022\022\n\nisLastPage\030\007 \001(\010\022\027\n\017" +
      "hasPreviousPage\030\010 \001(\010\022\023\n\013hasNextPage\030\t \001" +
      "(\010\"\032\n\007Founder\022\017\n\007founder\030\001 \001(\003\"$\n\017Dynami" +
      "cIdResult\022\021\n\tdynamicId\030\001 \001(\003\"\225\001\n\024MomentD" +
      "ynamicPublish\022\021\n\tdynamicId\030\001 \001(\003\022\021\n\tpubl" +
      "ishBy\030\002 \001(\003\0222\n\013publishType\030\003 \001(\0162\035.MOMEN" +
      "TS_DYNAMIC_PUBLISH_TYPE\022\021\n\tlongitude\030\004 \001" +
      "(\001\022\020\n\010latitude\030\005 \001(\001*G\n\034MOMENTS_DYNAMIC_" +
      "PUBLISH_TYPE\022\014\n\010ORDINARY\020\000\022\014\n\010ORIGINAL\020\001" +
      "\022\013\n\007REPRINT\020\002B9\n5com.upuphub.dew.communi" +
      "ty.connection.protobuf.momentsP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_MomentDynamicContent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MomentDynamicContent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MomentDynamicContent_descriptor,
        new java.lang.String[] { "Uin", "Longitude", "Latitude", "Dynamic", "Pictures", "Topic", "Classify", "UpdateTime", "DynamicContentId", });
    internal_static_DynamicContentResultCell_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_DynamicContentResultCell_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DynamicContentResultCell_descriptor,
        new java.lang.String[] { "DynamicContentId", "Longitude", "Latitude", "Dynamic", "Pictures", "Topic", "Classify", "PublishTime", "OriginUin", "LikeNumber", "PublishType", });
    internal_static_DynamicsContentResult_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_DynamicsContentResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DynamicsContentResult_descriptor,
        new java.lang.String[] { "DynamicContentCells", "PageInfo", });
    internal_static_DynamicHistoryRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_DynamicHistoryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DynamicHistoryRequest_descriptor,
        new java.lang.String[] { "Founder", "PageSize", "PageNum", });
    internal_static_PageInfo_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_PageInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PageInfo_descriptor,
        new java.lang.String[] { "PageNum", "PageSize", "Size", "Total", "Pages", "IsFirstPage", "IsLastPage", "HasPreviousPage", "HasNextPage", });
    internal_static_Founder_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_Founder_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Founder_descriptor,
        new java.lang.String[] { "Founder", });
    internal_static_DynamicIdResult_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_DynamicIdResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DynamicIdResult_descriptor,
        new java.lang.String[] { "DynamicId", });
    internal_static_MomentDynamicPublish_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_MomentDynamicPublish_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MomentDynamicPublish_descriptor,
        new java.lang.String[] { "DynamicId", "PublishBy", "PublishType", "Longitude", "Latitude", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
