// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: moments.proto

package com.upuphub.dew.community.connection.protobuf.moments;

public interface MomentDynamicContentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MomentDynamicContent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 uin = 1;</code>
   */
  long getUin();

  /**
   * <code>double longitude = 2;</code>
   */
  double getLongitude();

  /**
   * <code>double latitude = 3;</code>
   */
  double getLatitude();

  /**
   * <code>string dynamic = 4;</code>
   */
  java.lang.String getDynamic();
  /**
   * <code>string dynamic = 4;</code>
   */
  com.google.protobuf.ByteString
      getDynamicBytes();

  /**
   * <code>repeated string pictures = 5;</code>
   */
  java.util.List<java.lang.String>
      getPicturesList();
  /**
   * <code>repeated string pictures = 5;</code>
   */
  int getPicturesCount();
  /**
   * <code>repeated string pictures = 5;</code>
   */
  java.lang.String getPictures(int index);
  /**
   * <code>repeated string pictures = 5;</code>
   */
  com.google.protobuf.ByteString
      getPicturesBytes(int index);

  /**
   * <code>string topic = 6;</code>
   */
  java.lang.String getTopic();
  /**
   * <code>string topic = 6;</code>
   */
  com.google.protobuf.ByteString
      getTopicBytes();

  /**
   * <code>int32 classify = 7;</code>
   */
  int getClassify();
}
