// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: moments.proto

package com.upuphub.dew.community.connection.protobuf.moments;

/**
 * Protobuf type {@code MomentDynamicPublish}
 */
public  final class MomentDynamicPublish extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:MomentDynamicPublish)
    MomentDynamicPublishOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MomentDynamicPublish.newBuilder() to construct.
  private MomentDynamicPublish(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MomentDynamicPublish() {
    publishType_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MomentDynamicPublish();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MomentDynamicPublish(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            dynamicId_ = input.readInt64();
            break;
          }
          case 16: {

            publishBy_ = input.readInt64();
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            publishType_ = rawValue;
            break;
          }
          case 33: {

            longitude_ = input.readDouble();
            break;
          }
          case 41: {

            latitude_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.upuphub.dew.community.connection.protobuf.moments.Moments.internal_static_MomentDynamicPublish_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.upuphub.dew.community.connection.protobuf.moments.Moments.internal_static_MomentDynamicPublish_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.upuphub.dew.community.connection.protobuf.moments.MomentDynamicPublish.class, com.upuphub.dew.community.connection.protobuf.moments.MomentDynamicPublish.Builder.class);
  }

  public static final int DYNAMICID_FIELD_NUMBER = 1;
  private long dynamicId_;
  /**
   * <pre>
   * Dynamic Content ID
   * </pre>
   *
   * <code>int64 dynamicId = 1;</code>
   */
  public long getDynamicId() {
    return dynamicId_;
  }

  public static final int PUBLISHBY_FIELD_NUMBER = 2;
  private long publishBy_;
  /**
   * <pre>
   * 用户动态发布者ID
   * </pre>
   *
   * <code>int64 publishBy = 2;</code>
   */
  public long getPublishBy() {
    return publishBy_;
  }

  public static final int PUBLISHTYPE_FIELD_NUMBER = 3;
  private int publishType_;
  /**
   * <pre>
   * 动态的发布类型
   * </pre>
   *
   * <code>.MOMENTS_DYNAMIC_PUBLISH_TYPE publishType = 3;</code>
   */
  public int getPublishTypeValue() {
    return publishType_;
  }
  /**
   * <pre>
   * 动态的发布类型
   * </pre>
   *
   * <code>.MOMENTS_DYNAMIC_PUBLISH_TYPE publishType = 3;</code>
   */
  public com.upuphub.dew.community.connection.protobuf.moments.MOMENTS_DYNAMIC_PUBLISH_TYPE getPublishType() {
    @SuppressWarnings("deprecation")
    com.upuphub.dew.community.connection.protobuf.moments.MOMENTS_DYNAMIC_PUBLISH_TYPE result = com.upuphub.dew.community.connection.protobuf.moments.MOMENTS_DYNAMIC_PUBLISH_TYPE.valueOf(publishType_);
    return result == null ? com.upuphub.dew.community.connection.protobuf.moments.MOMENTS_DYNAMIC_PUBLISH_TYPE.UNRECOGNIZED : result;
  }

  public static final int LONGITUDE_FIELD_NUMBER = 4;
  private double longitude_;
  /**
   * <pre>
   * 用户发布消息的经度
   * </pre>
   *
   * <code>double longitude = 4;</code>
   */
  public double getLongitude() {
    return longitude_;
  }

  public static final int LATITUDE_FIELD_NUMBER = 5;
  private double latitude_;
  /**
   * <pre>
   * 用户发布消息的纬度
   * </pre>
   *
   * <code>double latitude = 5;</code>
   */
  public double getLatitude() {
    return latitude_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (dynamicId_ != 0L) {
      output.writeInt64(1, dynamicId_);
    }
    if (publishBy_ != 0L) {
      output.writeInt64(2, publishBy_);
    }
    if (publishType_ != com.upuphub.dew.community.connection.protobuf.moments.MOMENTS_DYNAMIC_PUBLISH_TYPE.ORDINARY.getNumber()) {
      output.writeEnum(3, publishType_);
    }
    if (longitude_ != 0D) {
      output.writeDouble(4, longitude_);
    }
    if (latitude_ != 0D) {
      output.writeDouble(5, latitude_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (dynamicId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, dynamicId_);
    }
    if (publishBy_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, publishBy_);
    }
    if (publishType_ != com.upuphub.dew.community.connection.protobuf.moments.MOMENTS_DYNAMIC_PUBLISH_TYPE.ORDINARY.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, publishType_);
    }
    if (longitude_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, longitude_);
    }
    if (latitude_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, latitude_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.upuphub.dew.community.connection.protobuf.moments.MomentDynamicPublish)) {
      return super.equals(obj);
    }
    com.upuphub.dew.community.connection.protobuf.moments.MomentDynamicPublish other = (com.upuphub.dew.community.connection.protobuf.moments.MomentDynamicPublish) obj;

    if (getDynamicId()
        != other.getDynamicId()) return false;
    if (getPublishBy()
        != other.getPublishBy()) return false;
    if (publishType_ != other.publishType_) return false;
    if (java.lang.Double.doubleToLongBits(getLongitude())
        != java.lang.Double.doubleToLongBits(
            other.getLongitude())) return false;
    if (java.lang.Double.doubleToLongBits(getLatitude())
        != java.lang.Double.doubleToLongBits(
            other.getLatitude())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DYNAMICID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDynamicId());
    hash = (37 * hash) + PUBLISHBY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPublishBy());
    hash = (37 * hash) + PUBLISHTYPE_FIELD_NUMBER;
    hash = (53 * hash) + publishType_;
    hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getLongitude()));
    hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getLatitude()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.upuphub.dew.community.connection.protobuf.moments.MomentDynamicPublish parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.upuphub.dew.community.connection.protobuf.moments.MomentDynamicPublish parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.upuphub.dew.community.connection.protobuf.moments.MomentDynamicPublish parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.upuphub.dew.community.connection.protobuf.moments.MomentDynamicPublish parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.upuphub.dew.community.connection.protobuf.moments.MomentDynamicPublish parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.upuphub.dew.community.connection.protobuf.moments.MomentDynamicPublish parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.upuphub.dew.community.connection.protobuf.moments.MomentDynamicPublish parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.upuphub.dew.community.connection.protobuf.moments.MomentDynamicPublish parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.upuphub.dew.community.connection.protobuf.moments.MomentDynamicPublish parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.upuphub.dew.community.connection.protobuf.moments.MomentDynamicPublish parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.upuphub.dew.community.connection.protobuf.moments.MomentDynamicPublish parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.upuphub.dew.community.connection.protobuf.moments.MomentDynamicPublish parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.upuphub.dew.community.connection.protobuf.moments.MomentDynamicPublish prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code MomentDynamicPublish}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:MomentDynamicPublish)
      com.upuphub.dew.community.connection.protobuf.moments.MomentDynamicPublishOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.upuphub.dew.community.connection.protobuf.moments.Moments.internal_static_MomentDynamicPublish_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.upuphub.dew.community.connection.protobuf.moments.Moments.internal_static_MomentDynamicPublish_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.upuphub.dew.community.connection.protobuf.moments.MomentDynamicPublish.class, com.upuphub.dew.community.connection.protobuf.moments.MomentDynamicPublish.Builder.class);
    }

    // Construct using com.upuphub.dew.community.connection.protobuf.moments.MomentDynamicPublish.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      dynamicId_ = 0L;

      publishBy_ = 0L;

      publishType_ = 0;

      longitude_ = 0D;

      latitude_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.upuphub.dew.community.connection.protobuf.moments.Moments.internal_static_MomentDynamicPublish_descriptor;
    }

    @java.lang.Override
    public com.upuphub.dew.community.connection.protobuf.moments.MomentDynamicPublish getDefaultInstanceForType() {
      return com.upuphub.dew.community.connection.protobuf.moments.MomentDynamicPublish.getDefaultInstance();
    }

    @java.lang.Override
    public com.upuphub.dew.community.connection.protobuf.moments.MomentDynamicPublish build() {
      com.upuphub.dew.community.connection.protobuf.moments.MomentDynamicPublish result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.upuphub.dew.community.connection.protobuf.moments.MomentDynamicPublish buildPartial() {
      com.upuphub.dew.community.connection.protobuf.moments.MomentDynamicPublish result = new com.upuphub.dew.community.connection.protobuf.moments.MomentDynamicPublish(this);
      result.dynamicId_ = dynamicId_;
      result.publishBy_ = publishBy_;
      result.publishType_ = publishType_;
      result.longitude_ = longitude_;
      result.latitude_ = latitude_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.upuphub.dew.community.connection.protobuf.moments.MomentDynamicPublish) {
        return mergeFrom((com.upuphub.dew.community.connection.protobuf.moments.MomentDynamicPublish)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.upuphub.dew.community.connection.protobuf.moments.MomentDynamicPublish other) {
      if (other == com.upuphub.dew.community.connection.protobuf.moments.MomentDynamicPublish.getDefaultInstance()) return this;
      if (other.getDynamicId() != 0L) {
        setDynamicId(other.getDynamicId());
      }
      if (other.getPublishBy() != 0L) {
        setPublishBy(other.getPublishBy());
      }
      if (other.publishType_ != 0) {
        setPublishTypeValue(other.getPublishTypeValue());
      }
      if (other.getLongitude() != 0D) {
        setLongitude(other.getLongitude());
      }
      if (other.getLatitude() != 0D) {
        setLatitude(other.getLatitude());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.upuphub.dew.community.connection.protobuf.moments.MomentDynamicPublish parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.upuphub.dew.community.connection.protobuf.moments.MomentDynamicPublish) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long dynamicId_ ;
    /**
     * <pre>
     * Dynamic Content ID
     * </pre>
     *
     * <code>int64 dynamicId = 1;</code>
     */
    public long getDynamicId() {
      return dynamicId_;
    }
    /**
     * <pre>
     * Dynamic Content ID
     * </pre>
     *
     * <code>int64 dynamicId = 1;</code>
     */
    public Builder setDynamicId(long value) {
      
      dynamicId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Dynamic Content ID
     * </pre>
     *
     * <code>int64 dynamicId = 1;</code>
     */
    public Builder clearDynamicId() {
      
      dynamicId_ = 0L;
      onChanged();
      return this;
    }

    private long publishBy_ ;
    /**
     * <pre>
     * 用户动态发布者ID
     * </pre>
     *
     * <code>int64 publishBy = 2;</code>
     */
    public long getPublishBy() {
      return publishBy_;
    }
    /**
     * <pre>
     * 用户动态发布者ID
     * </pre>
     *
     * <code>int64 publishBy = 2;</code>
     */
    public Builder setPublishBy(long value) {
      
      publishBy_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户动态发布者ID
     * </pre>
     *
     * <code>int64 publishBy = 2;</code>
     */
    public Builder clearPublishBy() {
      
      publishBy_ = 0L;
      onChanged();
      return this;
    }

    private int publishType_ = 0;
    /**
     * <pre>
     * 动态的发布类型
     * </pre>
     *
     * <code>.MOMENTS_DYNAMIC_PUBLISH_TYPE publishType = 3;</code>
     */
    public int getPublishTypeValue() {
      return publishType_;
    }
    /**
     * <pre>
     * 动态的发布类型
     * </pre>
     *
     * <code>.MOMENTS_DYNAMIC_PUBLISH_TYPE publishType = 3;</code>
     */
    public Builder setPublishTypeValue(int value) {
      publishType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 动态的发布类型
     * </pre>
     *
     * <code>.MOMENTS_DYNAMIC_PUBLISH_TYPE publishType = 3;</code>
     */
    public com.upuphub.dew.community.connection.protobuf.moments.MOMENTS_DYNAMIC_PUBLISH_TYPE getPublishType() {
      @SuppressWarnings("deprecation")
      com.upuphub.dew.community.connection.protobuf.moments.MOMENTS_DYNAMIC_PUBLISH_TYPE result = com.upuphub.dew.community.connection.protobuf.moments.MOMENTS_DYNAMIC_PUBLISH_TYPE.valueOf(publishType_);
      return result == null ? com.upuphub.dew.community.connection.protobuf.moments.MOMENTS_DYNAMIC_PUBLISH_TYPE.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 动态的发布类型
     * </pre>
     *
     * <code>.MOMENTS_DYNAMIC_PUBLISH_TYPE publishType = 3;</code>
     */
    public Builder setPublishType(com.upuphub.dew.community.connection.protobuf.moments.MOMENTS_DYNAMIC_PUBLISH_TYPE value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      publishType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 动态的发布类型
     * </pre>
     *
     * <code>.MOMENTS_DYNAMIC_PUBLISH_TYPE publishType = 3;</code>
     */
    public Builder clearPublishType() {
      
      publishType_ = 0;
      onChanged();
      return this;
    }

    private double longitude_ ;
    /**
     * <pre>
     * 用户发布消息的经度
     * </pre>
     *
     * <code>double longitude = 4;</code>
     */
    public double getLongitude() {
      return longitude_;
    }
    /**
     * <pre>
     * 用户发布消息的经度
     * </pre>
     *
     * <code>double longitude = 4;</code>
     */
    public Builder setLongitude(double value) {
      
      longitude_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户发布消息的经度
     * </pre>
     *
     * <code>double longitude = 4;</code>
     */
    public Builder clearLongitude() {
      
      longitude_ = 0D;
      onChanged();
      return this;
    }

    private double latitude_ ;
    /**
     * <pre>
     * 用户发布消息的纬度
     * </pre>
     *
     * <code>double latitude = 5;</code>
     */
    public double getLatitude() {
      return latitude_;
    }
    /**
     * <pre>
     * 用户发布消息的纬度
     * </pre>
     *
     * <code>double latitude = 5;</code>
     */
    public Builder setLatitude(double value) {
      
      latitude_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户发布消息的纬度
     * </pre>
     *
     * <code>double latitude = 5;</code>
     */
    public Builder clearLatitude() {
      
      latitude_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:MomentDynamicPublish)
  }

  // @@protoc_insertion_point(class_scope:MomentDynamicPublish)
  private static final com.upuphub.dew.community.connection.protobuf.moments.MomentDynamicPublish DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.upuphub.dew.community.connection.protobuf.moments.MomentDynamicPublish();
  }

  public static com.upuphub.dew.community.connection.protobuf.moments.MomentDynamicPublish getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MomentDynamicPublish>
      PARSER = new com.google.protobuf.AbstractParser<MomentDynamicPublish>() {
    @java.lang.Override
    public MomentDynamicPublish parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MomentDynamicPublish(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MomentDynamicPublish> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MomentDynamicPublish> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.upuphub.dew.community.connection.protobuf.moments.MomentDynamicPublish getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

