// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: moments.proto

package com.upuphub.dew.community.connection.protobuf.moments;

/**
 * Protobuf enum {@code MOMENTS_DYNAMIC_PUBLISH_TYPE}
 */
public enum MOMENTS_DYNAMIC_PUBLISH_TYPE
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * 普通
   * </pre>
   *
   * <code>ORDINARY = 0;</code>
   */
  ORDINARY(0),
  /**
   * <pre>
   * 原创
   * </pre>
   *
   * <code>ORIGINAL = 1;</code>
   */
  ORIGINAL(1),
  /**
   * <pre>
   * 转载
   * </pre>
   *
   * <code>REPRINT = 2;</code>
   */
  REPRINT(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * 普通
   * </pre>
   *
   * <code>ORDINARY = 0;</code>
   */
  public static final int ORDINARY_VALUE = 0;
  /**
   * <pre>
   * 原创
   * </pre>
   *
   * <code>ORIGINAL = 1;</code>
   */
  public static final int ORIGINAL_VALUE = 1;
  /**
   * <pre>
   * 转载
   * </pre>
   *
   * <code>REPRINT = 2;</code>
   */
  public static final int REPRINT_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static MOMENTS_DYNAMIC_PUBLISH_TYPE valueOf(int value) {
    return forNumber(value);
  }

  public static MOMENTS_DYNAMIC_PUBLISH_TYPE forNumber(int value) {
    switch (value) {
      case 0: return ORDINARY;
      case 1: return ORIGINAL;
      case 2: return REPRINT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<MOMENTS_DYNAMIC_PUBLISH_TYPE>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      MOMENTS_DYNAMIC_PUBLISH_TYPE> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<MOMENTS_DYNAMIC_PUBLISH_TYPE>() {
          public MOMENTS_DYNAMIC_PUBLISH_TYPE findValueByNumber(int number) {
            return MOMENTS_DYNAMIC_PUBLISH_TYPE.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.upuphub.dew.community.connection.protobuf.moments.Moments.getDescriptor().getEnumTypes().get(0);
  }

  private static final MOMENTS_DYNAMIC_PUBLISH_TYPE[] VALUES = values();

  public static MOMENTS_DYNAMIC_PUBLISH_TYPE valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private MOMENTS_DYNAMIC_PUBLISH_TYPE(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:MOMENTS_DYNAMIC_PUBLISH_TYPE)
}

