// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: moments.proto

package com.upuphub.dew.community.connection.protobuf.moments;

/**
 * Protobuf type {@code PageInfo}
 */
public  final class PageInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PageInfo)
    PageInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PageInfo.newBuilder() to construct.
  private PageInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PageInfo() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PageInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PageInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            pageNum_ = input.readInt32();
            break;
          }
          case 16: {

            pageSize_ = input.readInt32();
            break;
          }
          case 24: {

            size_ = input.readInt32();
            break;
          }
          case 32: {

            total_ = input.readInt64();
            break;
          }
          case 40: {

            pages_ = input.readInt32();
            break;
          }
          case 48: {

            isFirstPage_ = input.readBool();
            break;
          }
          case 56: {

            isLastPage_ = input.readBool();
            break;
          }
          case 64: {

            hasPreviousPage_ = input.readBool();
            break;
          }
          case 72: {

            hasNextPage_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.upuphub.dew.community.connection.protobuf.moments.Moments.internal_static_PageInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.upuphub.dew.community.connection.protobuf.moments.Moments.internal_static_PageInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.upuphub.dew.community.connection.protobuf.moments.PageInfo.class, com.upuphub.dew.community.connection.protobuf.moments.PageInfo.Builder.class);
  }

  public static final int PAGENUM_FIELD_NUMBER = 1;
  private int pageNum_;
  /**
   * <pre>
   * 当前页
   * </pre>
   *
   * <code>int32 pageNum = 1;</code>
   */
  public int getPageNum() {
    return pageNum_;
  }

  public static final int PAGESIZE_FIELD_NUMBER = 2;
  private int pageSize_;
  /**
   * <pre>
   * 每页的数量
   * </pre>
   *
   * <code>int32 pageSize = 2;</code>
   */
  public int getPageSize() {
    return pageSize_;
  }

  public static final int SIZE_FIELD_NUMBER = 3;
  private int size_;
  /**
   * <pre>
   *当前页的数量
   * </pre>
   *
   * <code>int32 size = 3;</code>
   */
  public int getSize() {
    return size_;
  }

  public static final int TOTAL_FIELD_NUMBER = 4;
  private long total_;
  /**
   * <pre>
   * 总记录数
   * </pre>
   *
   * <code>int64 total = 4;</code>
   */
  public long getTotal() {
    return total_;
  }

  public static final int PAGES_FIELD_NUMBER = 5;
  private int pages_;
  /**
   * <pre>
   * 总页码数
   * </pre>
   *
   * <code>int32 pages = 5;</code>
   */
  public int getPages() {
    return pages_;
  }

  public static final int ISFIRSTPAGE_FIELD_NUMBER = 6;
  private boolean isFirstPage_;
  /**
   * <pre>
   * 是否是第一页
   * </pre>
   *
   * <code>bool isFirstPage = 6;</code>
   */
  public boolean getIsFirstPage() {
    return isFirstPage_;
  }

  public static final int ISLASTPAGE_FIELD_NUMBER = 7;
  private boolean isLastPage_;
  /**
   * <pre>
   * 是否是最后一页
   * </pre>
   *
   * <code>bool isLastPage = 7;</code>
   */
  public boolean getIsLastPage() {
    return isLastPage_;
  }

  public static final int HASPREVIOUSPAGE_FIELD_NUMBER = 8;
  private boolean hasPreviousPage_;
  /**
   * <pre>
   * 是否有上一页
   * </pre>
   *
   * <code>bool hasPreviousPage = 8;</code>
   */
  public boolean getHasPreviousPage() {
    return hasPreviousPage_;
  }

  public static final int HASNEXTPAGE_FIELD_NUMBER = 9;
  private boolean hasNextPage_;
  /**
   * <pre>
   * 是否有下一页
   * </pre>
   *
   * <code>bool hasNextPage = 9;</code>
   */
  public boolean getHasNextPage() {
    return hasNextPage_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (pageNum_ != 0) {
      output.writeInt32(1, pageNum_);
    }
    if (pageSize_ != 0) {
      output.writeInt32(2, pageSize_);
    }
    if (size_ != 0) {
      output.writeInt32(3, size_);
    }
    if (total_ != 0L) {
      output.writeInt64(4, total_);
    }
    if (pages_ != 0) {
      output.writeInt32(5, pages_);
    }
    if (isFirstPage_ != false) {
      output.writeBool(6, isFirstPage_);
    }
    if (isLastPage_ != false) {
      output.writeBool(7, isLastPage_);
    }
    if (hasPreviousPage_ != false) {
      output.writeBool(8, hasPreviousPage_);
    }
    if (hasNextPage_ != false) {
      output.writeBool(9, hasNextPage_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (pageNum_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, pageNum_);
    }
    if (pageSize_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, pageSize_);
    }
    if (size_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, size_);
    }
    if (total_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, total_);
    }
    if (pages_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, pages_);
    }
    if (isFirstPage_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, isFirstPage_);
    }
    if (isLastPage_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, isLastPage_);
    }
    if (hasPreviousPage_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, hasPreviousPage_);
    }
    if (hasNextPage_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(9, hasNextPage_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.upuphub.dew.community.connection.protobuf.moments.PageInfo)) {
      return super.equals(obj);
    }
    com.upuphub.dew.community.connection.protobuf.moments.PageInfo other = (com.upuphub.dew.community.connection.protobuf.moments.PageInfo) obj;

    if (getPageNum()
        != other.getPageNum()) return false;
    if (getPageSize()
        != other.getPageSize()) return false;
    if (getSize()
        != other.getSize()) return false;
    if (getTotal()
        != other.getTotal()) return false;
    if (getPages()
        != other.getPages()) return false;
    if (getIsFirstPage()
        != other.getIsFirstPage()) return false;
    if (getIsLastPage()
        != other.getIsLastPage()) return false;
    if (getHasPreviousPage()
        != other.getHasPreviousPage()) return false;
    if (getHasNextPage()
        != other.getHasNextPage()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PAGENUM_FIELD_NUMBER;
    hash = (53 * hash) + getPageNum();
    hash = (37 * hash) + PAGESIZE_FIELD_NUMBER;
    hash = (53 * hash) + getPageSize();
    hash = (37 * hash) + SIZE_FIELD_NUMBER;
    hash = (53 * hash) + getSize();
    hash = (37 * hash) + TOTAL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTotal());
    hash = (37 * hash) + PAGES_FIELD_NUMBER;
    hash = (53 * hash) + getPages();
    hash = (37 * hash) + ISFIRSTPAGE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsFirstPage());
    hash = (37 * hash) + ISLASTPAGE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsLastPage());
    hash = (37 * hash) + HASPREVIOUSPAGE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getHasPreviousPage());
    hash = (37 * hash) + HASNEXTPAGE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getHasNextPage());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.upuphub.dew.community.connection.protobuf.moments.PageInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.upuphub.dew.community.connection.protobuf.moments.PageInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.upuphub.dew.community.connection.protobuf.moments.PageInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.upuphub.dew.community.connection.protobuf.moments.PageInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.upuphub.dew.community.connection.protobuf.moments.PageInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.upuphub.dew.community.connection.protobuf.moments.PageInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.upuphub.dew.community.connection.protobuf.moments.PageInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.upuphub.dew.community.connection.protobuf.moments.PageInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.upuphub.dew.community.connection.protobuf.moments.PageInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.upuphub.dew.community.connection.protobuf.moments.PageInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.upuphub.dew.community.connection.protobuf.moments.PageInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.upuphub.dew.community.connection.protobuf.moments.PageInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.upuphub.dew.community.connection.protobuf.moments.PageInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PageInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PageInfo)
      com.upuphub.dew.community.connection.protobuf.moments.PageInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.upuphub.dew.community.connection.protobuf.moments.Moments.internal_static_PageInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.upuphub.dew.community.connection.protobuf.moments.Moments.internal_static_PageInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.upuphub.dew.community.connection.protobuf.moments.PageInfo.class, com.upuphub.dew.community.connection.protobuf.moments.PageInfo.Builder.class);
    }

    // Construct using com.upuphub.dew.community.connection.protobuf.moments.PageInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      pageNum_ = 0;

      pageSize_ = 0;

      size_ = 0;

      total_ = 0L;

      pages_ = 0;

      isFirstPage_ = false;

      isLastPage_ = false;

      hasPreviousPage_ = false;

      hasNextPage_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.upuphub.dew.community.connection.protobuf.moments.Moments.internal_static_PageInfo_descriptor;
    }

    @java.lang.Override
    public com.upuphub.dew.community.connection.protobuf.moments.PageInfo getDefaultInstanceForType() {
      return com.upuphub.dew.community.connection.protobuf.moments.PageInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.upuphub.dew.community.connection.protobuf.moments.PageInfo build() {
      com.upuphub.dew.community.connection.protobuf.moments.PageInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.upuphub.dew.community.connection.protobuf.moments.PageInfo buildPartial() {
      com.upuphub.dew.community.connection.protobuf.moments.PageInfo result = new com.upuphub.dew.community.connection.protobuf.moments.PageInfo(this);
      result.pageNum_ = pageNum_;
      result.pageSize_ = pageSize_;
      result.size_ = size_;
      result.total_ = total_;
      result.pages_ = pages_;
      result.isFirstPage_ = isFirstPage_;
      result.isLastPage_ = isLastPage_;
      result.hasPreviousPage_ = hasPreviousPage_;
      result.hasNextPage_ = hasNextPage_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.upuphub.dew.community.connection.protobuf.moments.PageInfo) {
        return mergeFrom((com.upuphub.dew.community.connection.protobuf.moments.PageInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.upuphub.dew.community.connection.protobuf.moments.PageInfo other) {
      if (other == com.upuphub.dew.community.connection.protobuf.moments.PageInfo.getDefaultInstance()) return this;
      if (other.getPageNum() != 0) {
        setPageNum(other.getPageNum());
      }
      if (other.getPageSize() != 0) {
        setPageSize(other.getPageSize());
      }
      if (other.getSize() != 0) {
        setSize(other.getSize());
      }
      if (other.getTotal() != 0L) {
        setTotal(other.getTotal());
      }
      if (other.getPages() != 0) {
        setPages(other.getPages());
      }
      if (other.getIsFirstPage() != false) {
        setIsFirstPage(other.getIsFirstPage());
      }
      if (other.getIsLastPage() != false) {
        setIsLastPage(other.getIsLastPage());
      }
      if (other.getHasPreviousPage() != false) {
        setHasPreviousPage(other.getHasPreviousPage());
      }
      if (other.getHasNextPage() != false) {
        setHasNextPage(other.getHasNextPage());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.upuphub.dew.community.connection.protobuf.moments.PageInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.upuphub.dew.community.connection.protobuf.moments.PageInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int pageNum_ ;
    /**
     * <pre>
     * 当前页
     * </pre>
     *
     * <code>int32 pageNum = 1;</code>
     */
    public int getPageNum() {
      return pageNum_;
    }
    /**
     * <pre>
     * 当前页
     * </pre>
     *
     * <code>int32 pageNum = 1;</code>
     */
    public Builder setPageNum(int value) {
      
      pageNum_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 当前页
     * </pre>
     *
     * <code>int32 pageNum = 1;</code>
     */
    public Builder clearPageNum() {
      
      pageNum_ = 0;
      onChanged();
      return this;
    }

    private int pageSize_ ;
    /**
     * <pre>
     * 每页的数量
     * </pre>
     *
     * <code>int32 pageSize = 2;</code>
     */
    public int getPageSize() {
      return pageSize_;
    }
    /**
     * <pre>
     * 每页的数量
     * </pre>
     *
     * <code>int32 pageSize = 2;</code>
     */
    public Builder setPageSize(int value) {
      
      pageSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 每页的数量
     * </pre>
     *
     * <code>int32 pageSize = 2;</code>
     */
    public Builder clearPageSize() {
      
      pageSize_ = 0;
      onChanged();
      return this;
    }

    private int size_ ;
    /**
     * <pre>
     *当前页的数量
     * </pre>
     *
     * <code>int32 size = 3;</code>
     */
    public int getSize() {
      return size_;
    }
    /**
     * <pre>
     *当前页的数量
     * </pre>
     *
     * <code>int32 size = 3;</code>
     */
    public Builder setSize(int value) {
      
      size_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *当前页的数量
     * </pre>
     *
     * <code>int32 size = 3;</code>
     */
    public Builder clearSize() {
      
      size_ = 0;
      onChanged();
      return this;
    }

    private long total_ ;
    /**
     * <pre>
     * 总记录数
     * </pre>
     *
     * <code>int64 total = 4;</code>
     */
    public long getTotal() {
      return total_;
    }
    /**
     * <pre>
     * 总记录数
     * </pre>
     *
     * <code>int64 total = 4;</code>
     */
    public Builder setTotal(long value) {
      
      total_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 总记录数
     * </pre>
     *
     * <code>int64 total = 4;</code>
     */
    public Builder clearTotal() {
      
      total_ = 0L;
      onChanged();
      return this;
    }

    private int pages_ ;
    /**
     * <pre>
     * 总页码数
     * </pre>
     *
     * <code>int32 pages = 5;</code>
     */
    public int getPages() {
      return pages_;
    }
    /**
     * <pre>
     * 总页码数
     * </pre>
     *
     * <code>int32 pages = 5;</code>
     */
    public Builder setPages(int value) {
      
      pages_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 总页码数
     * </pre>
     *
     * <code>int32 pages = 5;</code>
     */
    public Builder clearPages() {
      
      pages_ = 0;
      onChanged();
      return this;
    }

    private boolean isFirstPage_ ;
    /**
     * <pre>
     * 是否是第一页
     * </pre>
     *
     * <code>bool isFirstPage = 6;</code>
     */
    public boolean getIsFirstPage() {
      return isFirstPage_;
    }
    /**
     * <pre>
     * 是否是第一页
     * </pre>
     *
     * <code>bool isFirstPage = 6;</code>
     */
    public Builder setIsFirstPage(boolean value) {
      
      isFirstPage_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 是否是第一页
     * </pre>
     *
     * <code>bool isFirstPage = 6;</code>
     */
    public Builder clearIsFirstPage() {
      
      isFirstPage_ = false;
      onChanged();
      return this;
    }

    private boolean isLastPage_ ;
    /**
     * <pre>
     * 是否是最后一页
     * </pre>
     *
     * <code>bool isLastPage = 7;</code>
     */
    public boolean getIsLastPage() {
      return isLastPage_;
    }
    /**
     * <pre>
     * 是否是最后一页
     * </pre>
     *
     * <code>bool isLastPage = 7;</code>
     */
    public Builder setIsLastPage(boolean value) {
      
      isLastPage_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 是否是最后一页
     * </pre>
     *
     * <code>bool isLastPage = 7;</code>
     */
    public Builder clearIsLastPage() {
      
      isLastPage_ = false;
      onChanged();
      return this;
    }

    private boolean hasPreviousPage_ ;
    /**
     * <pre>
     * 是否有上一页
     * </pre>
     *
     * <code>bool hasPreviousPage = 8;</code>
     */
    public boolean getHasPreviousPage() {
      return hasPreviousPage_;
    }
    /**
     * <pre>
     * 是否有上一页
     * </pre>
     *
     * <code>bool hasPreviousPage = 8;</code>
     */
    public Builder setHasPreviousPage(boolean value) {
      
      hasPreviousPage_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 是否有上一页
     * </pre>
     *
     * <code>bool hasPreviousPage = 8;</code>
     */
    public Builder clearHasPreviousPage() {
      
      hasPreviousPage_ = false;
      onChanged();
      return this;
    }

    private boolean hasNextPage_ ;
    /**
     * <pre>
     * 是否有下一页
     * </pre>
     *
     * <code>bool hasNextPage = 9;</code>
     */
    public boolean getHasNextPage() {
      return hasNextPage_;
    }
    /**
     * <pre>
     * 是否有下一页
     * </pre>
     *
     * <code>bool hasNextPage = 9;</code>
     */
    public Builder setHasNextPage(boolean value) {
      
      hasNextPage_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 是否有下一页
     * </pre>
     *
     * <code>bool hasNextPage = 9;</code>
     */
    public Builder clearHasNextPage() {
      
      hasNextPage_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:PageInfo)
  }

  // @@protoc_insertion_point(class_scope:PageInfo)
  private static final com.upuphub.dew.community.connection.protobuf.moments.PageInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.upuphub.dew.community.connection.protobuf.moments.PageInfo();
  }

  public static com.upuphub.dew.community.connection.protobuf.moments.PageInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PageInfo>
      PARSER = new com.google.protobuf.AbstractParser<PageInfo>() {
    @java.lang.Override
    public PageInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PageInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PageInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PageInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.upuphub.dew.community.connection.protobuf.moments.PageInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

