server:
  port: 8796

spring:
  application:
    name: dew-smart-community-relation
  cloud:
      # SpringCloud-Alibaba-Nacos服务注册中心配置
    nacos:
      discovery:
        server-addr: support.upuphub.com:8848

logging:
  level:
    root: debug


management:
  endpoints:
    web:
      exposure:
        include: "*"