server:
  port: 8695

spring:
  application:
    name: dew-smart-community-relation
  cloud:
      # SpringCloud-Alibaba-Nacos服务注册中心配置
    nacos:
      discovery:
        server-addr: support.upuphub.com:8848

  datasource:
    url: jdbc:mysql://10.147.20.20:3306/dew_relation?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    name: dew_relation
    username: Leo
    password: A!@#456bnm
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

dew:
  mqtt:
    username: DewRelationSvr001@155
    password: DewRelationSvr001@155
    # 推送信息的连接地址，如果有多个，用逗号隔开，如：tcp://127.0.0.1:61613,tcp://192.168.1.61:616
    url: tcp://support.upuphub.com:6788 #tcp://119.3.147.11:19099
    producer:
      # 连接服务器默认客户端ID
      clientId: DewRelation@Producer
      # 默认的推送主题，实际可在调用接口时指定
      defaultTopic: DEW_RELATION_TOPIC

logging:
  level:
    root: debug


management:
  endpoints:
    web:
      exposure:
        include: "*"