# Spring相关设置
spring:
  application:
    # 模块服务名称
    name: dew-smart-community-account
  cloud:
    # SpringCloud-Alibaba-Nacos服务注册中心配置
    nacos:
      discovery:
        server-addr: 119.3.147.11:8848
  # Mysql数据库-服务配置
  datasource:
    url: jdbc:mysql://localhost:3306/rbc_account?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    name: rbc_account
    username: rubbish
    password: Pwd2Rbc_DB
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    # mongodb数据库-服务配置
    mongodb:
      uri: mongodb://119.3.147.11:27018/dew_account
# 服务端口
server:
  port: 8762

# Mybatis Mapper服务配置
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

# QuickProfile 配置文件配置
profiles:
  config:
    xmlPath: classpath:/profile/Profile.xml

# Dew 服务器相关配置
dew:
  password:
    salt: RUBBISH-COMMUNITY-SVR
  mqtt:
    topic:
      template: Dew:User:%s
    username: DewAccount
    password: DewAccount
    # 推送信息的连接地址，如果有多个，用逗号隔开，如：tcp://127.0.0.1:61613,tcp://192.168.1.61:616
    url: tcp://119.3.147.11:19099
    producer:
      # 连接服务器默认客户端ID
      clientId: AccountProducer
      # 默认的推送主题，实际可在调用接口时指定
      defaultTopic: RBC_API_SVR
    consumer:
      # 连接服务器默认客户端ID
      clientId: AccountConsumer
      # 默认的接收主题，可以订阅多个Topic，逗号分隔
      defaultTopic: System


management:
  endpoints:
    web:
      exposure:
        include: "*"