// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mqtt.proto

package com.upuphub.dew.community.connection.protobuf.mqtt;

public interface MqttMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MqttMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 tag = 1;</code>
   */
  int getTag();

  /**
   * <code>int32 type = 2;</code>
   */
  int getType();

  /**
   * <code>bytes payload = 3;</code>
   */
  com.google.protobuf.ByteString getPayload();

  /**
   * <code>string messageId = 4;</code>
   */
  java.lang.String getMessageId();
  /**
   * <code>string messageId = 4;</code>
   */
  com.google.protobuf.ByteString
      getMessageIdBytes();
}
