// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mqtt.proto

package com.upuphub.dew.community.connection.protobuf.mqtt;

public final class Mqtt {
  private Mqtt() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MqttMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MqttMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProfileMapMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProfileMapMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProfileMapMessage_ProfileEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProfileMapMessage_ProfileEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nmqtt.proto\"L\n\013MqttMessage\022\013\n\003tag\030\001 \001(\005" +
      "\022\014\n\004type\030\002 \001(\005\022\017\n\007payload\030\003 \001(\014\022\021\n\tmessa" +
      "geId\030\004 \001(\t\"\202\001\n\021ProfileMapMessage\022\013\n\003uin\030" +
      "\001 \001(\003\0220\n\007profile\030\002 \003(\0132\037.ProfileMapMessa" +
      "ge.ProfileEntry\032.\n\014ProfileEntry\022\013\n\003key\030\001" +
      " \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001B6\n2com.upuphub.d" +
      "ew.community.connection.protobuf.mqttP\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_MqttMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MqttMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MqttMessage_descriptor,
        new java.lang.String[] { "Tag", "Type", "Payload", "MessageId", });
    internal_static_ProfileMapMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ProfileMapMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProfileMapMessage_descriptor,
        new java.lang.String[] { "Uin", "Profile", });
    internal_static_ProfileMapMessage_ProfileEntry_descriptor =
      internal_static_ProfileMapMessage_descriptor.getNestedTypes().get(0);
    internal_static_ProfileMapMessage_ProfileEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProfileMapMessage_ProfileEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
