server:
  port: 8682


spring:
  application:
    name: dew-smart-community-push
  cloud:
      # SpringCloud-Alibaba-Nacos服务注册中心配置
    nacos:
      discovery:
        ip: 10.147.20.215
        server-addr: support.upuphub.com:8848

  mail:
    host: smtp.163.com
    username: Corlizi@163.com
    password: Password2Mail
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: dew_push
    password: A!@#456bnm
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://10.147.20.20:3306/dew_push?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: Leo

logging:
  level:
    root: debug

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/*Mapper.xml

##################
#  MQTT 配置
##################
push:
  mailgun:
    api-key: 03f60638f75fcac2879af85d43642a43-aa4b0867-4da10346
    domain: support.upuphub.com
    url: https://api.mailgun.net/v3/%s/messages


  mqtt:
    syncOnline: true
    username: DewPushSvr001@155
    password: DewPushSvr001@155
    # 推送信息的连接地址，如果有多个，用逗号隔开，如：tcp://127.0.0.1:61613,tcp://192.168.1.61:616
    url: tcp://support.upuphub.com:6788 #tcp://119.3.147.11:19099
    producer:
      # 连接服务器默认客户端ID
      clientId: PushDevProducer
      # 默认的推送主题，实际可在调用接口时指定
      defaultTopic: SystemDev
    consumer:
      # 连接服务器默认客户端ID
      clientId: DewPushSvr001@Consumer
      # 默认的接收主题，可以订阅多个Topic，逗号分隔
      defaultTopic: DEW_RELATION_TOPIC

management:
  endpoints:
    web:
      exposure:
        include: "*"