// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.upuphub.dew.community.connection.protobuf.common;

public interface RpcResultCodeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RpcResultCode)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   */
  int getCode();
}
